/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPropertiesRouteImport } from './routes/api/properties'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiDistrictsRouteImport } from './routes/api/districts'
import { Route as ApiAnalysisRouteImport } from './routes/api/analysis'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesRoute = ApiPropertiesRouteImport.update({
  id: '/api/properties',
  path: '/api/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDistrictsRoute = ApiDistrictsRouteImport.update({
  id: '/api/districts',
  path: '/api/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisRoute = ApiAnalysisRouteImport.update({
  id: '/api/analysis',
  path: '/api/analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/watchlist': typeof WatchlistRoute
  '/api/analysis': typeof ApiAnalysisRoute
  '/api/districts': typeof ApiDistrictsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/properties': typeof ApiPropertiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/watchlist': typeof WatchlistRoute
  '/api/analysis': typeof ApiAnalysisRoute
  '/api/districts': typeof ApiDistrictsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/properties': typeof ApiPropertiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/watchlist': typeof WatchlistRoute
  '/api/analysis': typeof ApiAnalysisRoute
  '/api/districts': typeof ApiDistrictsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/properties': typeof ApiPropertiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/compare'
    | '/history'
    | '/watchlist'
    | '/api/analysis'
    | '/api/districts'
    | '/api/history'
    | '/api/properties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/compare'
    | '/history'
    | '/watchlist'
    | '/api/analysis'
    | '/api/districts'
    | '/api/history'
    | '/api/properties'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/compare'
    | '/history'
    | '/watchlist'
    | '/api/analysis'
    | '/api/districts'
    | '/api/history'
    | '/api/properties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CompareRoute: typeof CompareRoute
  HistoryRoute: typeof HistoryRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiAnalysisRoute: typeof ApiAnalysisRoute
  ApiDistrictsRoute: typeof ApiDistrictsRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiPropertiesRoute: typeof ApiPropertiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties': {
      id: '/api/properties'
      path: '/api/properties'
      fullPath: '/api/properties'
      preLoaderRoute: typeof ApiPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/districts': {
      id: '/api/districts'
      path: '/api/districts'
      fullPath: '/api/districts'
      preLoaderRoute: typeof ApiDistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis': {
      id: '/api/analysis'
      path: '/api/analysis'
      fullPath: '/api/analysis'
      preLoaderRoute: typeof ApiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  CompareRoute: CompareRoute,
  HistoryRoute: HistoryRoute,
  WatchlistRoute: WatchlistRoute,
  ApiAnalysisRoute: ApiAnalysisRoute,
  ApiDistrictsRoute: ApiDistrictsRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiPropertiesRoute: ApiPropertiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
