import { expect, test } from "bun:test";
import { isWrapperUserText } from "./user-text";

test("machine-generated wrappers are not mistaken for the user's own words", () => {
    // Measured on this machine before the shared filter existed: of 111 Codex sessions, 60 opened
    // with `# AGENTS.md`, 30 with `<environment_context>` and 18 with `<user_instructions>`. Only
    // the first was filtered, so 48 sessions listed a machine blob as their first prompt.
    for (const wrapper of [
        "# AGENTS.md instructions for /Users/me/project",
        "<user_info>\nOS Version: macos\n</user_info>",
        "<user_instructions>\n# Frontend\n</user_instructions>",
        "<environment_context>\n  <cwd>/Users/me/project</cwd>\n</environment_context>",
        "<git_status>\nbranch main\n</git_status>",
        "<turn_aborted>The user interrupted the turn</turn_aborted>",
        "   <environment_context>leading whitespace still counts</environment_context>",
    ]) {
        expect(isWrapperUserText(wrapper)).toBe(true);
    }

    for (const prompt of [
        "hello",
        "please rebase this branch",
        "explain <environment_context> to me",
        "# AGENTS is a file I want to discuss",
        "",
    ]) {
        expect(isWrapperUserText(prompt)).toBe(false);
    }
});

test("Claude Code plumbing is filtered but a slash command still names itself", () => {
    // 253 of 1,588 indexed Claude sessions opened with a tag or heading; these four cover 147.
    for (const wrapper of [
        "<local-command-caveat>Caveat: The messages below were generated by the user",
        '<teammate-message teammate_id="team-lead"> Review the diff',
        "<system-reminder>\nThe user named this session\n</system-reminder>",
        "## Context Usage\n**Model:** claude-opus",
    ]) {
        expect(isWrapperUserText(wrapper)).toBe(true);
    }

    // The user did invoke this, and the command name is more use in a listing than what follows.
    expect(isWrapperUserText("<command-message>research</command-message>")).toBe(false);
    expect(isWrapperUserText("## Context for the refactor I want")).toBe(false);
});
