/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSetupRouteImport } from './routes/dashboard.setup'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard.devices'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/devices'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/devices'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/devices'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
