/** The `tools macos clones` landing text. Explains the model the flags assume;
 *  `--help` lists the flags themselves. */
export function clonesGuide(): string {
    return [
        "tools macos clones — clone-aware disk usage and safe dedupe (macOS/APFS)",
        "",
        "THE NUMBERS",
        "  du -sh counts every clone copy in full. real counts the bytes that would",
        "  actually be freed if you deleted the tree now. A bun-installed",
        "  node_modules is mostly clones of the install cache, so du overstates it,",
        "  often several times over. Start with: tools macos clones measure <dir>",
        "",
        "WHY WORKTREES LOOK HUGE",
        "  bun install clonefiles from its cache, so the first checkout is nearly",
        "  free. A postinstall that copies a file (native .a bundles do this) writes",
        "  a private full copy instead, and every worktree pays for it again. Those",
        "  private copies are what reclaim collapses back into shared extents.",
        "",
        "THE VERBS",
        "  measure     clone-aware sizes for a tree (real, du, overcount)",
        "  du          the same, shaped like du",
        "  duplicates  content-identical files and dirs that are NOT yet clones",
        "  optimize    the low-level door: you name the roots, it plans, --apply acts",
        "  reclaim     the fleet door: name a directory, it finds the trees for you",
        "  config      watched dirs and defaults",
        "  daemon      background report-only scans",
        "",
        "RECLAIM",
        "  tools macos clones reclaim plan --dir ~/Projects/Acme",
        "  tools macos clones reclaim plan --dir ~/Projects/Acme --worktrees-of app",
        "  tools macos clones reclaim apply --dir ~/Projects/Acme --yes",
        "  tools macos clones reclaim presets save acme --dir ~/Projects/Acme",
        "  tools macos clones reclaim presets run acme --apply",
        "",
        "  --dir           where to look (a repo, or a parent of many checkouts)",
        "  --worktrees-of  resolve that repo's git worktrees, including siblings",
        "                  that do not live under --dir",
        "  --targets       which trees to scan. Default: the gitignored install",
        "                  dirs (node_modules, composer vendor, Pods, .cxx).",
        "                  Pass the flag with no value to see the choices.",
        "",
        "TWO THINGS CALLED A PLAN",
        "  preset   the selector you saved (--save <id>). It stores what you typed,",
        "           never file paths, and every run rediscovers the trees. Re-run it",
        "           for months: after a branch switch the packages differ, and only",
        "           rediscovery is correct.",
        "  snapshot the keep/replace list, cached for 1 hour with the mtime of each",
        "           root. An apply that follows a plan reuses it only while every",
        "           root is unchanged; otherwise it rescans. Never replayed a day",
        "           later.",
        "  Speed on a later run comes from the per-file metadata cache, which skips",
        "  hashing files whose size and mtime did not move.",
        "",
        "PACKAGE-MANAGER STORES",
        "  bun, npm, pnpm, yarn and composer caches are keep-only: a file inside one",
        "  can win as the copy everything else points at, and is never written.",
        "  They join a set only with --keep-partners, and only bun can currently",
        "  resolve a candidate; the others report their root and nothing else.",
        "",
        "SAFETY",
        "  Dry-run is the default; apply is a separate verb and asks for a typed",
        "  confirmation. Every clone is byte-compared first, swapped atomically, and",
        "  re-hashed after. Undo a run with:",
        "    tools macos clones optimize --rollback --process <id>",
        "",
        "WHERE THE LOGS ARE",
        "  ~/.genesis-tools/logs/<date>.log                  everything, pino JSON",
        "  ~/.genesis-tools/macos-clones/reclaim/<id>.jsonl  what a reclaim run saw",
        "  ~/.genesis-tools/macos-clones/process/<id>.jsonl  what an apply changed",
        "  ~/.genesis-tools/logs/<date>-profiling.log        phase timings",
        "  Phase timings need PROFILE=clones in the environment; PROFILE=clones",
        "  with profiling.detail=all also times each spawned command and directory.",
    ].join("\n");
}
