import type { YoutubeDatabase } from "@app/youtube/lib/db";
import type { ArtifactKind } from "@app/youtube/lib/users.types";
import { CREDIT_COSTS, REUSE_COST } from "@app/youtube/lib/users.types";

/**
 * Price a user pays for an artifact:
 * - already owned/unlocked (access row exists) → 0
 * - exists but generated by somebody else → flat `REUSE_COST`, `reused: true`
 * - missing → full generation price from `CREDIT_COSTS`
 */
export function resolveArtifactPrice(
    db: YoutubeDatabase,
    opts: { userId: number; kind: ArtifactKind; videoId: string }
): { price: number; reused: boolean } {
    if (db.hasArtifactAccess(opts.userId, opts.kind, opts.videoId)) {
        return { price: 0, reused: false };
    }

    if (db.hasArtifact(opts.kind, opts.videoId)) {
        return { price: REUSE_COST, reused: true };
    }

    return { price: generationCost(opts.kind), reused: false };
}

/** Records access; idempotent — repeat grants keep the original row. */
export function grantArtifactAccess(
    db: YoutubeDatabase,
    opts: { userId: number; kind: ArtifactKind; videoId: string; creditsSpent: number }
): void {
    db.insertArtifactAccess(opts);
}

function generationCost(kind: ArtifactKind): number {
    if (kind === "transcript:ai") {
        // No route charges credits for AI transcription yet, so there is no
        // generation price to quote — reuse/access rows for this kind still work.
        throw new Error("no generation credit cost defined for transcript:ai");
    }

    return CREDIT_COSTS[kind];
}
