/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiEventsRouteImport } from "./routes/api.events";
import { Route as ApiTrpcSplatRouteImport } from "./routes/api.trpc.$";
import { Route as AssistantAnalyticsRouteImport } from "./routes/assistant/analytics";
import { Route as AssistantCommunicationRouteImport } from "./routes/assistant/communication";
import { Route as AssistantDecisionsRouteImport } from "./routes/assistant/decisions";
import { Route as AssistantIndexRouteImport } from "./routes/assistant/index";
import { Route as AssistantNextRouteImport } from "./routes/assistant/next";
import { Route as AssistantParkingRouteImport } from "./routes/assistant/parking";
import { Route as AssistantTasksTaskIdRouteImport } from "./routes/assistant/tasks/$taskId";
import { Route as AssistantTasksIndexRouteImport } from "./routes/assistant/tasks/index";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthErrorRouteImport } from "./routes/auth/error";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthSigninRouteImport } from "./routes/auth/signin";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as DashboardAiRouteImport } from "./routes/dashboard/ai";
import { Route as DashboardBookmarksRouteImport } from "./routes/dashboard/bookmarks";
import { Route as DashboardFocusRouteImport } from "./routes/dashboard/focus";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as DashboardNotesRouteImport } from "./routes/dashboard/notes";
import { Route as DashboardPlannerRouteImport } from "./routes/dashboard/planner";
import { Route as ExampleTodoRouteImport } from "./routes/example/todo";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as McpRouteImport } from "./routes/mcp";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as TimerIndexRouteImport } from "./routes/timer/index";
import { Route as TimerTimerIdRouteImport } from "./routes/timer.$timerId";

const SettingsRoute = SettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => rootRouteImport,
} as any);
const McpRoute = McpRouteImport.update({
    id: "/mcp",
    path: "/mcp",
    getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const TimerIndexRoute = TimerIndexRouteImport.update({
    id: "/timer/",
    path: "/timer/",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
    id: "/dashboard/",
    path: "/dashboard/",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantIndexRoute = AssistantIndexRouteImport.update({
    id: "/assistant/",
    path: "/assistant/",
    getParentRoute: () => rootRouteImport,
} as any);
const TimerTimerIdRoute = TimerTimerIdRouteImport.update({
    id: "/timer/$timerId",
    path: "/timer/$timerId",
    getParentRoute: () => rootRouteImport,
} as any);
const ExampleTodoRoute = ExampleTodoRouteImport.update({
    id: "/example/todo",
    path: "/example/todo",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
    id: "/dashboard/planner",
    path: "/dashboard/planner",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardNotesRoute = DashboardNotesRouteImport.update({
    id: "/dashboard/notes",
    path: "/dashboard/notes",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardFocusRoute = DashboardFocusRouteImport.update({
    id: "/dashboard/focus",
    path: "/dashboard/focus",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
    id: "/dashboard/bookmarks",
    path: "/dashboard/bookmarks",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardAiRoute = DashboardAiRouteImport.update({
    id: "/dashboard/ai",
    path: "/dashboard/ai",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
    id: "/auth/signup",
    path: "/auth/signup",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthSigninRoute = AuthSigninRouteImport.update({
    id: "/auth/signin",
    path: "/auth/signin",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
    id: "/auth/reset-password",
    path: "/auth/reset-password",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
    id: "/auth/forgot-password",
    path: "/auth/forgot-password",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthErrorRoute = AuthErrorRouteImport.update({
    id: "/auth/error",
    path: "/auth/error",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
    id: "/auth/callback",
    path: "/auth/callback",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantParkingRoute = AssistantParkingRouteImport.update({
    id: "/assistant/parking",
    path: "/assistant/parking",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantNextRoute = AssistantNextRouteImport.update({
    id: "/assistant/next",
    path: "/assistant/next",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantDecisionsRoute = AssistantDecisionsRouteImport.update({
    id: "/assistant/decisions",
    path: "/assistant/decisions",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantCommunicationRoute = AssistantCommunicationRouteImport.update({
    id: "/assistant/communication",
    path: "/assistant/communication",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantAnalyticsRoute = AssistantAnalyticsRouteImport.update({
    id: "/assistant/analytics",
    path: "/assistant/analytics",
    getParentRoute: () => rootRouteImport,
} as any);
const ApiEventsRoute = ApiEventsRouteImport.update({
    id: "/api/events",
    path: "/api/events",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantTasksIndexRoute = AssistantTasksIndexRouteImport.update({
    id: "/assistant/tasks/",
    path: "/assistant/tasks/",
    getParentRoute: () => rootRouteImport,
} as any);
const AssistantTasksTaskIdRoute = AssistantTasksTaskIdRouteImport.update({
    id: "/assistant/tasks/$taskId",
    path: "/assistant/tasks/$taskId",
    getParentRoute: () => rootRouteImport,
} as any);
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
    id: "/api/trpc/$",
    path: "/api/trpc/$",
    getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/mcp": typeof McpRoute;
    "/profile": typeof ProfileRoute;
    "/settings": typeof SettingsRoute;
    "/api/events": typeof ApiEventsRoute;
    "/assistant/analytics": typeof AssistantAnalyticsRoute;
    "/assistant/communication": typeof AssistantCommunicationRoute;
    "/assistant/decisions": typeof AssistantDecisionsRoute;
    "/assistant/next": typeof AssistantNextRoute;
    "/assistant/parking": typeof AssistantParkingRoute;
    "/auth/callback": typeof AuthCallbackRoute;
    "/auth/error": typeof AuthErrorRoute;
    "/auth/forgot-password": typeof AuthForgotPasswordRoute;
    "/auth/reset-password": typeof AuthResetPasswordRoute;
    "/auth/signin": typeof AuthSigninRoute;
    "/auth/signup": typeof AuthSignupRoute;
    "/dashboard/ai": typeof DashboardAiRoute;
    "/dashboard/bookmarks": typeof DashboardBookmarksRoute;
    "/dashboard/focus": typeof DashboardFocusRoute;
    "/dashboard/notes": typeof DashboardNotesRoute;
    "/dashboard/planner": typeof DashboardPlannerRoute;
    "/example/todo": typeof ExampleTodoRoute;
    "/timer/$timerId": typeof TimerTimerIdRoute;
    "/assistant": typeof AssistantIndexRoute;
    "/dashboard": typeof DashboardIndexRoute;
    "/timer": typeof TimerIndexRoute;
    "/api/trpc/$": typeof ApiTrpcSplatRoute;
    "/assistant/tasks/$taskId": typeof AssistantTasksTaskIdRoute;
    "/assistant/tasks": typeof AssistantTasksIndexRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/mcp": typeof McpRoute;
    "/profile": typeof ProfileRoute;
    "/settings": typeof SettingsRoute;
    "/api/events": typeof ApiEventsRoute;
    "/assistant/analytics": typeof AssistantAnalyticsRoute;
    "/assistant/communication": typeof AssistantCommunicationRoute;
    "/assistant/decisions": typeof AssistantDecisionsRoute;
    "/assistant/next": typeof AssistantNextRoute;
    "/assistant/parking": typeof AssistantParkingRoute;
    "/auth/callback": typeof AuthCallbackRoute;
    "/auth/error": typeof AuthErrorRoute;
    "/auth/forgot-password": typeof AuthForgotPasswordRoute;
    "/auth/reset-password": typeof AuthResetPasswordRoute;
    "/auth/signin": typeof AuthSigninRoute;
    "/auth/signup": typeof AuthSignupRoute;
    "/dashboard/ai": typeof DashboardAiRoute;
    "/dashboard/bookmarks": typeof DashboardBookmarksRoute;
    "/dashboard/focus": typeof DashboardFocusRoute;
    "/dashboard/notes": typeof DashboardNotesRoute;
    "/dashboard/planner": typeof DashboardPlannerRoute;
    "/example/todo": typeof ExampleTodoRoute;
    "/timer/$timerId": typeof TimerTimerIdRoute;
    "/assistant": typeof AssistantIndexRoute;
    "/dashboard": typeof DashboardIndexRoute;
    "/timer": typeof TimerIndexRoute;
    "/api/trpc/$": typeof ApiTrpcSplatRoute;
    "/assistant/tasks/$taskId": typeof AssistantTasksTaskIdRoute;
    "/assistant/tasks": typeof AssistantTasksIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/mcp": typeof McpRoute;
    "/profile": typeof ProfileRoute;
    "/settings": typeof SettingsRoute;
    "/api/events": typeof ApiEventsRoute;
    "/assistant/analytics": typeof AssistantAnalyticsRoute;
    "/assistant/communication": typeof AssistantCommunicationRoute;
    "/assistant/decisions": typeof AssistantDecisionsRoute;
    "/assistant/next": typeof AssistantNextRoute;
    "/assistant/parking": typeof AssistantParkingRoute;
    "/auth/callback": typeof AuthCallbackRoute;
    "/auth/error": typeof AuthErrorRoute;
    "/auth/forgot-password": typeof AuthForgotPasswordRoute;
    "/auth/reset-password": typeof AuthResetPasswordRoute;
    "/auth/signin": typeof AuthSigninRoute;
    "/auth/signup": typeof AuthSignupRoute;
    "/dashboard/ai": typeof DashboardAiRoute;
    "/dashboard/bookmarks": typeof DashboardBookmarksRoute;
    "/dashboard/focus": typeof DashboardFocusRoute;
    "/dashboard/notes": typeof DashboardNotesRoute;
    "/dashboard/planner": typeof DashboardPlannerRoute;
    "/example/todo": typeof ExampleTodoRoute;
    "/timer/$timerId": typeof TimerTimerIdRoute;
    "/assistant/": typeof AssistantIndexRoute;
    "/dashboard/": typeof DashboardIndexRoute;
    "/timer/": typeof TimerIndexRoute;
    "/api/trpc/$": typeof ApiTrpcSplatRoute;
    "/assistant/tasks/$taskId": typeof AssistantTasksTaskIdRoute;
    "/assistant/tasks/": typeof AssistantTasksIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | "/"
        | "/mcp"
        | "/profile"
        | "/settings"
        | "/api/events"
        | "/assistant/analytics"
        | "/assistant/communication"
        | "/assistant/decisions"
        | "/assistant/next"
        | "/assistant/parking"
        | "/auth/callback"
        | "/auth/error"
        | "/auth/forgot-password"
        | "/auth/reset-password"
        | "/auth/signin"
        | "/auth/signup"
        | "/dashboard/ai"
        | "/dashboard/bookmarks"
        | "/dashboard/focus"
        | "/dashboard/notes"
        | "/dashboard/planner"
        | "/example/todo"
        | "/timer/$timerId"
        | "/assistant"
        | "/dashboard"
        | "/timer"
        | "/api/trpc/$"
        | "/assistant/tasks/$taskId"
        | "/assistant/tasks";
    fileRoutesByTo: FileRoutesByTo;
    to:
        | "/"
        | "/mcp"
        | "/profile"
        | "/settings"
        | "/api/events"
        | "/assistant/analytics"
        | "/assistant/communication"
        | "/assistant/decisions"
        | "/assistant/next"
        | "/assistant/parking"
        | "/auth/callback"
        | "/auth/error"
        | "/auth/forgot-password"
        | "/auth/reset-password"
        | "/auth/signin"
        | "/auth/signup"
        | "/dashboard/ai"
        | "/dashboard/bookmarks"
        | "/dashboard/focus"
        | "/dashboard/notes"
        | "/dashboard/planner"
        | "/example/todo"
        | "/timer/$timerId"
        | "/assistant"
        | "/dashboard"
        | "/timer"
        | "/api/trpc/$"
        | "/assistant/tasks/$taskId"
        | "/assistant/tasks";
    id:
        | "__root__"
        | "/"
        | "/mcp"
        | "/profile"
        | "/settings"
        | "/api/events"
        | "/assistant/analytics"
        | "/assistant/communication"
        | "/assistant/decisions"
        | "/assistant/next"
        | "/assistant/parking"
        | "/auth/callback"
        | "/auth/error"
        | "/auth/forgot-password"
        | "/auth/reset-password"
        | "/auth/signin"
        | "/auth/signup"
        | "/dashboard/ai"
        | "/dashboard/bookmarks"
        | "/dashboard/focus"
        | "/dashboard/notes"
        | "/dashboard/planner"
        | "/example/todo"
        | "/timer/$timerId"
        | "/assistant/"
        | "/dashboard/"
        | "/timer/"
        | "/api/trpc/$"
        | "/assistant/tasks/$taskId"
        | "/assistant/tasks/";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    McpRoute: typeof McpRoute;
    ProfileRoute: typeof ProfileRoute;
    SettingsRoute: typeof SettingsRoute;
    ApiEventsRoute: typeof ApiEventsRoute;
    AssistantAnalyticsRoute: typeof AssistantAnalyticsRoute;
    AssistantCommunicationRoute: typeof AssistantCommunicationRoute;
    AssistantDecisionsRoute: typeof AssistantDecisionsRoute;
    AssistantNextRoute: typeof AssistantNextRoute;
    AssistantParkingRoute: typeof AssistantParkingRoute;
    AuthCallbackRoute: typeof AuthCallbackRoute;
    AuthErrorRoute: typeof AuthErrorRoute;
    AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
    AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
    AuthSigninRoute: typeof AuthSigninRoute;
    AuthSignupRoute: typeof AuthSignupRoute;
    DashboardAiRoute: typeof DashboardAiRoute;
    DashboardBookmarksRoute: typeof DashboardBookmarksRoute;
    DashboardFocusRoute: typeof DashboardFocusRoute;
    DashboardNotesRoute: typeof DashboardNotesRoute;
    DashboardPlannerRoute: typeof DashboardPlannerRoute;
    ExampleTodoRoute: typeof ExampleTodoRoute;
    TimerTimerIdRoute: typeof TimerTimerIdRoute;
    AssistantIndexRoute: typeof AssistantIndexRoute;
    DashboardIndexRoute: typeof DashboardIndexRoute;
    TimerIndexRoute: typeof TimerIndexRoute;
    ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute;
    AssistantTasksTaskIdRoute: typeof AssistantTasksTaskIdRoute;
    AssistantTasksIndexRoute: typeof AssistantTasksIndexRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/settings": {
            id: "/settings";
            path: "/settings";
            fullPath: "/settings";
            preLoaderRoute: typeof SettingsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/profile": {
            id: "/profile";
            path: "/profile";
            fullPath: "/profile";
            preLoaderRoute: typeof ProfileRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/mcp": {
            id: "/mcp";
            path: "/mcp";
            fullPath: "/mcp";
            preLoaderRoute: typeof McpRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/timer/": {
            id: "/timer/";
            path: "/timer";
            fullPath: "/timer";
            preLoaderRoute: typeof TimerIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/": {
            id: "/dashboard/";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/": {
            id: "/assistant/";
            path: "/assistant";
            fullPath: "/assistant";
            preLoaderRoute: typeof AssistantIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/timer/$timerId": {
            id: "/timer/$timerId";
            path: "/timer/$timerId";
            fullPath: "/timer/$timerId";
            preLoaderRoute: typeof TimerTimerIdRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/example/todo": {
            id: "/example/todo";
            path: "/example/todo";
            fullPath: "/example/todo";
            preLoaderRoute: typeof ExampleTodoRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/planner": {
            id: "/dashboard/planner";
            path: "/dashboard/planner";
            fullPath: "/dashboard/planner";
            preLoaderRoute: typeof DashboardPlannerRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/notes": {
            id: "/dashboard/notes";
            path: "/dashboard/notes";
            fullPath: "/dashboard/notes";
            preLoaderRoute: typeof DashboardNotesRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/focus": {
            id: "/dashboard/focus";
            path: "/dashboard/focus";
            fullPath: "/dashboard/focus";
            preLoaderRoute: typeof DashboardFocusRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/bookmarks": {
            id: "/dashboard/bookmarks";
            path: "/dashboard/bookmarks";
            fullPath: "/dashboard/bookmarks";
            preLoaderRoute: typeof DashboardBookmarksRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/ai": {
            id: "/dashboard/ai";
            path: "/dashboard/ai";
            fullPath: "/dashboard/ai";
            preLoaderRoute: typeof DashboardAiRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/signup": {
            id: "/auth/signup";
            path: "/auth/signup";
            fullPath: "/auth/signup";
            preLoaderRoute: typeof AuthSignupRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/signin": {
            id: "/auth/signin";
            path: "/auth/signin";
            fullPath: "/auth/signin";
            preLoaderRoute: typeof AuthSigninRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/reset-password": {
            id: "/auth/reset-password";
            path: "/auth/reset-password";
            fullPath: "/auth/reset-password";
            preLoaderRoute: typeof AuthResetPasswordRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/forgot-password": {
            id: "/auth/forgot-password";
            path: "/auth/forgot-password";
            fullPath: "/auth/forgot-password";
            preLoaderRoute: typeof AuthForgotPasswordRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/error": {
            id: "/auth/error";
            path: "/auth/error";
            fullPath: "/auth/error";
            preLoaderRoute: typeof AuthErrorRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/callback": {
            id: "/auth/callback";
            path: "/auth/callback";
            fullPath: "/auth/callback";
            preLoaderRoute: typeof AuthCallbackRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/parking": {
            id: "/assistant/parking";
            path: "/assistant/parking";
            fullPath: "/assistant/parking";
            preLoaderRoute: typeof AssistantParkingRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/next": {
            id: "/assistant/next";
            path: "/assistant/next";
            fullPath: "/assistant/next";
            preLoaderRoute: typeof AssistantNextRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/decisions": {
            id: "/assistant/decisions";
            path: "/assistant/decisions";
            fullPath: "/assistant/decisions";
            preLoaderRoute: typeof AssistantDecisionsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/communication": {
            id: "/assistant/communication";
            path: "/assistant/communication";
            fullPath: "/assistant/communication";
            preLoaderRoute: typeof AssistantCommunicationRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/analytics": {
            id: "/assistant/analytics";
            path: "/assistant/analytics";
            fullPath: "/assistant/analytics";
            preLoaderRoute: typeof AssistantAnalyticsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/api/events": {
            id: "/api/events";
            path: "/api/events";
            fullPath: "/api/events";
            preLoaderRoute: typeof ApiEventsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/tasks/": {
            id: "/assistant/tasks/";
            path: "/assistant/tasks";
            fullPath: "/assistant/tasks";
            preLoaderRoute: typeof AssistantTasksIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/assistant/tasks/$taskId": {
            id: "/assistant/tasks/$taskId";
            path: "/assistant/tasks/$taskId";
            fullPath: "/assistant/tasks/$taskId";
            preLoaderRoute: typeof AssistantTasksTaskIdRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/api/trpc/$": {
            id: "/api/trpc/$";
            path: "/api/trpc/$";
            fullPath: "/api/trpc/$";
            preLoaderRoute: typeof ApiTrpcSplatRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    McpRoute: McpRoute,
    ProfileRoute: ProfileRoute,
    SettingsRoute: SettingsRoute,
    ApiEventsRoute: ApiEventsRoute,
    AssistantAnalyticsRoute: AssistantAnalyticsRoute,
    AssistantCommunicationRoute: AssistantCommunicationRoute,
    AssistantDecisionsRoute: AssistantDecisionsRoute,
    AssistantNextRoute: AssistantNextRoute,
    AssistantParkingRoute: AssistantParkingRoute,
    AuthCallbackRoute: AuthCallbackRoute,
    AuthErrorRoute: AuthErrorRoute,
    AuthForgotPasswordRoute: AuthForgotPasswordRoute,
    AuthResetPasswordRoute: AuthResetPasswordRoute,
    AuthSigninRoute: AuthSigninRoute,
    AuthSignupRoute: AuthSignupRoute,
    DashboardAiRoute: DashboardAiRoute,
    DashboardBookmarksRoute: DashboardBookmarksRoute,
    DashboardFocusRoute: DashboardFocusRoute,
    DashboardNotesRoute: DashboardNotesRoute,
    DashboardPlannerRoute: DashboardPlannerRoute,
    ExampleTodoRoute: ExampleTodoRoute,
    TimerTimerIdRoute: TimerTimerIdRoute,
    AssistantIndexRoute: AssistantIndexRoute,
    DashboardIndexRoute: DashboardIndexRoute,
    TimerIndexRoute: TimerIndexRoute,
    ApiTrpcSplatRoute: ApiTrpcSplatRoute,
    AssistantTasksTaskIdRoute: AssistantTasksTaskIdRoute,
    AssistantTasksIndexRoute: AssistantTasksIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";

declare module "@tanstack/react-start" {
    interface Register {
        ssr: true;
        router: Awaited<ReturnType<typeof getRouter>>;
        config: Awaited<ReturnType<typeof startInstance.getOptions>>;
    }
}
