/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AssistantRouteRouteImport } from './routes/assistant/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimerIndexRouteImport } from './routes/timer/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AssistantIndexRouteImport } from './routes/assistant/index'
import { Route as TimerTimerIdRouteImport } from './routes/timer.$timerId'
import { Route as DashboardReadingRouteImport } from './routes/dashboard/reading'
import { Route as DashboardPlannerRouteImport } from './routes/dashboard/planner'
import { Route as DashboardNotesRouteImport } from './routes/dashboard/notes'
import { Route as DashboardMoodRouteImport } from './routes/dashboard/mood'
import { Route as DashboardHabitsRouteImport } from './routes/dashboard/habits'
import { Route as DashboardGoalsRouteImport } from './routes/dashboard/goals'
import { Route as DashboardFocusRouteImport } from './routes/dashboard/focus'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as DashboardBookmarksRouteImport } from './routes/dashboard/bookmarks'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AssistantParkingRouteImport } from './routes/assistant/parking'
import { Route as AssistantNextRouteImport } from './routes/assistant/next'
import { Route as AssistantDecisionsRouteImport } from './routes/assistant/decisions'
import { Route as AssistantCommunicationRouteImport } from './routes/assistant/communication'
import { Route as AssistantBlockersRouteImport } from './routes/assistant/blockers'
import { Route as AssistantAnalyticsRouteImport } from './routes/assistant/analytics'
import { Route as ApiTimerEventsRouteImport } from './routes/api.timer-events'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ApiAiChatRouteImport } from './routes/api.ai-chat'
import { Route as AssistantTasksIndexRouteImport } from './routes/assistant/tasks/index'
import { Route as AssistantTasksTaskIdRouteImport } from './routes/assistant/tasks/$taskId'
import { Route as ApiAvatarUserIdRouteImport } from './routes/api.avatar.$userId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRouteRoute = AssistantRouteRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerIndexRoute = TimerIndexRouteImport.update({
  id: '/timer/',
  path: '/timer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const TimerTimerIdRoute = TimerTimerIdRouteImport.update({
  id: '/timer/$timerId',
  path: '/timer/$timerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReadingRoute = DashboardReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMoodRoute = DashboardMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHabitsRoute = DashboardHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoalsRoute = DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFocusRoute = DashboardFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantParkingRoute = AssistantParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const AssistantNextRoute = AssistantNextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const AssistantDecisionsRoute = AssistantDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const AssistantCommunicationRoute = AssistantCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const AssistantBlockersRoute = AssistantBlockersRouteImport.update({
  id: '/blockers',
  path: '/blockers',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const AssistantAnalyticsRoute = AssistantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const ApiTimerEventsRoute = ApiTimerEventsRouteImport.update({
  id: '/api/timer-events',
  path: '/api/timer-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantTasksIndexRoute = AssistantTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const AssistantTasksTaskIdRoute = AssistantTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AssistantRouteRoute,
} as any)
const ApiAvatarUserIdRoute = ApiAvatarUserIdRouteImport.update({
  id: '/api/avatar/$userId',
  path: '/api/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/timer-events': typeof ApiTimerEventsRoute
  '/assistant/analytics': typeof AssistantAnalyticsRoute
  '/assistant/blockers': typeof AssistantBlockersRoute
  '/assistant/communication': typeof AssistantCommunicationRoute
  '/assistant/decisions': typeof AssistantDecisionsRoute
  '/assistant/next': typeof AssistantNextRoute
  '/assistant/parking': typeof AssistantParkingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/habits': typeof DashboardHabitsRoute
  '/dashboard/mood': typeof DashboardMoodRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/reading': typeof DashboardReadingRoute
  '/timer/$timerId': typeof TimerTimerIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/timer': typeof TimerIndexRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/assistant/tasks/$taskId': typeof AssistantTasksTaskIdRoute
  '/assistant/tasks': typeof AssistantTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/timer-events': typeof ApiTimerEventsRoute
  '/assistant/analytics': typeof AssistantAnalyticsRoute
  '/assistant/blockers': typeof AssistantBlockersRoute
  '/assistant/communication': typeof AssistantCommunicationRoute
  '/assistant/decisions': typeof AssistantDecisionsRoute
  '/assistant/next': typeof AssistantNextRoute
  '/assistant/parking': typeof AssistantParkingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/habits': typeof DashboardHabitsRoute
  '/dashboard/mood': typeof DashboardMoodRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/reading': typeof DashboardReadingRoute
  '/timer/$timerId': typeof TimerTimerIdRoute
  '/assistant': typeof AssistantIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/timer': typeof TimerIndexRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/assistant/tasks/$taskId': typeof AssistantTasksTaskIdRoute
  '/assistant/tasks': typeof AssistantTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/timer-events': typeof ApiTimerEventsRoute
  '/assistant/analytics': typeof AssistantAnalyticsRoute
  '/assistant/blockers': typeof AssistantBlockersRoute
  '/assistant/communication': typeof AssistantCommunicationRoute
  '/assistant/decisions': typeof AssistantDecisionsRoute
  '/assistant/next': typeof AssistantNextRoute
  '/assistant/parking': typeof AssistantParkingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/habits': typeof DashboardHabitsRoute
  '/dashboard/mood': typeof DashboardMoodRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/reading': typeof DashboardReadingRoute
  '/timer/$timerId': typeof TimerTimerIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/timer/': typeof TimerIndexRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/assistant/tasks/$taskId': typeof AssistantTasksTaskIdRoute
  '/assistant/tasks/': typeof AssistantTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/mcp'
    | '/profile'
    | '/settings'
    | '/api/ai-chat'
    | '/api/events'
    | '/api/health'
    | '/api/timer-events'
    | '/assistant/analytics'
    | '/assistant/blockers'
    | '/assistant/communication'
    | '/assistant/decisions'
    | '/assistant/next'
    | '/assistant/parking'
    | '/auth/callback'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/ai'
    | '/dashboard/bookmarks'
    | '/dashboard/expenses'
    | '/dashboard/focus'
    | '/dashboard/goals'
    | '/dashboard/habits'
    | '/dashboard/mood'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/reading'
    | '/timer/$timerId'
    | '/assistant/'
    | '/dashboard/'
    | '/timer'
    | '/api/avatar/$userId'
    | '/assistant/tasks/$taskId'
    | '/assistant/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/profile'
    | '/settings'
    | '/api/ai-chat'
    | '/api/events'
    | '/api/health'
    | '/api/timer-events'
    | '/assistant/analytics'
    | '/assistant/blockers'
    | '/assistant/communication'
    | '/assistant/decisions'
    | '/assistant/next'
    | '/assistant/parking'
    | '/auth/callback'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/ai'
    | '/dashboard/bookmarks'
    | '/dashboard/expenses'
    | '/dashboard/focus'
    | '/dashboard/goals'
    | '/dashboard/habits'
    | '/dashboard/mood'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/reading'
    | '/timer/$timerId'
    | '/assistant'
    | '/dashboard'
    | '/timer'
    | '/api/avatar/$userId'
    | '/assistant/tasks/$taskId'
    | '/assistant/tasks'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/mcp'
    | '/profile'
    | '/settings'
    | '/api/ai-chat'
    | '/api/events'
    | '/api/health'
    | '/api/timer-events'
    | '/assistant/analytics'
    | '/assistant/blockers'
    | '/assistant/communication'
    | '/assistant/decisions'
    | '/assistant/next'
    | '/assistant/parking'
    | '/auth/callback'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/ai'
    | '/dashboard/bookmarks'
    | '/dashboard/expenses'
    | '/dashboard/focus'
    | '/dashboard/goals'
    | '/dashboard/habits'
    | '/dashboard/mood'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/reading'
    | '/timer/$timerId'
    | '/assistant/'
    | '/dashboard/'
    | '/timer/'
    | '/api/avatar/$userId'
    | '/assistant/tasks/$taskId'
    | '/assistant/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRouteRoute: typeof AssistantRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  McpRoute: typeof McpRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTimerEventsRoute: typeof ApiTimerEventsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  TimerTimerIdRoute: typeof TimerTimerIdRoute
  TimerIndexRoute: typeof TimerIndexRoute
  ApiAvatarUserIdRoute: typeof ApiAvatarUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer/': {
      id: '/timer/'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/timer/$timerId': {
      id: '/timer/$timerId'
      path: '/timer/$timerId'
      fullPath: '/timer/$timerId'
      preLoaderRoute: typeof TimerTimerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reading': {
      id: '/dashboard/reading'
      path: '/reading'
      fullPath: '/dashboard/reading'
      preLoaderRoute: typeof DashboardReadingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/planner': {
      id: '/dashboard/planner'
      path: '/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof DashboardPlannerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/mood': {
      id: '/dashboard/mood'
      path: '/mood'
      fullPath: '/dashboard/mood'
      preLoaderRoute: typeof DashboardMoodRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/habits': {
      id: '/dashboard/habits'
      path: '/habits'
      fullPath: '/dashboard/habits'
      preLoaderRoute: typeof DashboardHabitsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/goals': {
      id: '/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/focus': {
      id: '/dashboard/focus'
      path: '/focus'
      fullPath: '/dashboard/focus'
      preLoaderRoute: typeof DashboardFocusRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bookmarks': {
      id: '/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardBookmarksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/parking': {
      id: '/assistant/parking'
      path: '/parking'
      fullPath: '/assistant/parking'
      preLoaderRoute: typeof AssistantParkingRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/assistant/next': {
      id: '/assistant/next'
      path: '/next'
      fullPath: '/assistant/next'
      preLoaderRoute: typeof AssistantNextRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/assistant/decisions': {
      id: '/assistant/decisions'
      path: '/decisions'
      fullPath: '/assistant/decisions'
      preLoaderRoute: typeof AssistantDecisionsRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/assistant/communication': {
      id: '/assistant/communication'
      path: '/communication'
      fullPath: '/assistant/communication'
      preLoaderRoute: typeof AssistantCommunicationRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/assistant/blockers': {
      id: '/assistant/blockers'
      path: '/blockers'
      fullPath: '/assistant/blockers'
      preLoaderRoute: typeof AssistantBlockersRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/assistant/analytics': {
      id: '/assistant/analytics'
      path: '/analytics'
      fullPath: '/assistant/analytics'
      preLoaderRoute: typeof AssistantAnalyticsRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/api/timer-events': {
      id: '/api/timer-events'
      path: '/api/timer-events'
      fullPath: '/api/timer-events'
      preLoaderRoute: typeof ApiTimerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/tasks/': {
      id: '/assistant/tasks/'
      path: '/tasks'
      fullPath: '/assistant/tasks'
      preLoaderRoute: typeof AssistantTasksIndexRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/assistant/tasks/$taskId': {
      id: '/assistant/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/assistant/tasks/$taskId'
      preLoaderRoute: typeof AssistantTasksTaskIdRouteImport
      parentRoute: typeof AssistantRouteRoute
    }
    '/api/avatar/$userId': {
      id: '/api/avatar/$userId'
      path: '/api/avatar/$userId'
      fullPath: '/api/avatar/$userId'
      preLoaderRoute: typeof ApiAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssistantRouteRouteChildren {
  AssistantAnalyticsRoute: typeof AssistantAnalyticsRoute
  AssistantBlockersRoute: typeof AssistantBlockersRoute
  AssistantCommunicationRoute: typeof AssistantCommunicationRoute
  AssistantDecisionsRoute: typeof AssistantDecisionsRoute
  AssistantNextRoute: typeof AssistantNextRoute
  AssistantParkingRoute: typeof AssistantParkingRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  AssistantTasksTaskIdRoute: typeof AssistantTasksTaskIdRoute
  AssistantTasksIndexRoute: typeof AssistantTasksIndexRoute
}

const AssistantRouteRouteChildren: AssistantRouteRouteChildren = {
  AssistantAnalyticsRoute: AssistantAnalyticsRoute,
  AssistantBlockersRoute: AssistantBlockersRoute,
  AssistantCommunicationRoute: AssistantCommunicationRoute,
  AssistantDecisionsRoute: AssistantDecisionsRoute,
  AssistantNextRoute: AssistantNextRoute,
  AssistantParkingRoute: AssistantParkingRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  AssistantTasksTaskIdRoute: AssistantTasksTaskIdRoute,
  AssistantTasksIndexRoute: AssistantTasksIndexRoute,
}

const AssistantRouteRouteWithChildren = AssistantRouteRoute._addFileChildren(
  AssistantRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardBookmarksRoute: typeof DashboardBookmarksRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardFocusRoute: typeof DashboardFocusRoute
  DashboardGoalsRoute: typeof DashboardGoalsRoute
  DashboardHabitsRoute: typeof DashboardHabitsRoute
  DashboardMoodRoute: typeof DashboardMoodRoute
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardPlannerRoute: typeof DashboardPlannerRoute
  DashboardReadingRoute: typeof DashboardReadingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardBookmarksRoute: DashboardBookmarksRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardFocusRoute: DashboardFocusRoute,
  DashboardGoalsRoute: DashboardGoalsRoute,
  DashboardHabitsRoute: DashboardHabitsRoute,
  DashboardMoodRoute: DashboardMoodRoute,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardPlannerRoute: DashboardPlannerRoute,
  DashboardReadingRoute: DashboardReadingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRouteRoute: AssistantRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  McpRoute: McpRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTimerEventsRoute: ApiTimerEventsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  TimerTimerIdRoute: TimerTimerIdRoute,
  TimerIndexRoute: TimerIndexRoute,
  ApiAvatarUserIdRoute: ApiAvatarUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
