import type { Command } from "commander";
import { registerAssistCommand } from "./assist";
import { registerAwaitCommand } from "./await";
import { registerCaptureCommands } from "./capture";
import { registerChooseCommand } from "./choose";
import { registerCompareScreenshotCommand } from "./compare-screenshot";
import { registerComputerUseCommands } from "./computer-use";
import { registerCursorCommands } from "./cursor";
import { registerDecisionCommands } from "./decision";
import { registerDiscoveryCommands } from "./discovery";
import { registerDrawCommand } from "./draw";
import { registerFillCommand } from "./fill";
import { registerInteractCommands } from "./interact";
import { registerObserveCommand } from "./observe";
import { registerOsascriptCommand } from "./osascript";
import { registerPermissionsCommands } from "./permissions";
import { registerRecordPlanCommand } from "./record-plan";
import { registerReplayCommand } from "./replay";
import { registerReplayPlanCommand } from "./replay-plan";
import { registerRunCommand } from "./run";
import { registerSequenceCommand } from "./sequence";
import { registerStateCommands } from "./state";
import { registerVerifyCommands } from "./verify";
import { registerVisualCommand } from "./visual";
import { registerWorkflowCommands } from "./workflow";

export function registerControlCommands(program: Command): void {
    registerCaptureCommands(program);
    registerAssistCommand(program);
    registerAwaitCommand(program);
    registerChooseCommand(program);
    registerComputerUseCommands(program);
    registerCompareScreenshotCommand(program);
    registerCursorCommands(program);
    registerDiscoveryCommands(program);
    registerDecisionCommands(program);
    registerOsascriptCommand(program);
    registerPermissionsCommands(program);
    registerDrawCommand(program);
    registerInteractCommands(program);
    registerObserveCommand(program);
    registerFillCommand(program);
    registerRecordPlanCommand(program);
    registerRunCommand(program);
    registerSequenceCommand(program);
    registerReplayCommand(program);
    registerReplayPlanCommand(program);
    registerStateCommands(program);
    registerVerifyCommands(program);
    registerVisualCommand(program);
    registerWorkflowCommands(program);
}
