import AppKit

/// nspasteboard.org markers. Clipboard-history apps (Raycast, Maccy, Paste) skip an item carrying
/// them, so the text of an automated paste does not land in the user's history, and an app that
/// re-publishes what it records has nothing of ours to re-publish.
public let clipboardTransientTypes = [
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
]

public final class ClipboardTransaction {
    private let board: NSPasteboard
    private let original: [[NSPasteboard.PasteboardType: Data]]
    private let initialCount: Int
    private var ownedCount: Int?
    private var ownedText: String?
    /// restore() can be reached from the main thread and from a termination handler at once.
    private let lock = NSLock()

    public init(board: NSPasteboard) throws {
        self.board = board
        initialCount = board.changeCount
        original = try (board.pasteboardItems ?? []).map { item in
            var values: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                guard let data = item.data(forType: type) else {
                    throw WindowEventError.unavailable("cannot preserve clipboard representation \(type.rawValue); clipboard unchanged")
                }
                values[type] = data
            }
            return values
        }
        guard board.changeCount == initialCount else {
            throw WindowEventError.unavailable("clipboard changed during preservation; no paste dispatched")
        }
    }

    /// True while the pasteboard holds our payload and a restore is still owed.
    public var owesRestore: Bool {
        lock.lock()
        defer { lock.unlock() }
        return ownedCount != nil
    }

    public func write(text: String, format: String) throws {
        lock.lock()
        defer { lock.unlock() }
        guard ["text", "md", "html"].contains(format), board.changeCount == initialCount, ownedCount == nil else {
            throw WindowEventError.unavailable("invalid paste format or clipboard changed before paste")
        }
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if format == "html" { item.setString(text, forType: .html) }
        if format == "md" { item.setString(text, forType: NSPasteboard.PasteboardType("net.daringfireball.markdown")) }
        for marker in clipboardTransientTypes { item.setData(Data(), forType: marker) }
        guard board.changeCount == initialCount else {
            throw WindowEventError.unavailable("clipboard changed while preparing paste; no paste dispatched")
        }
        ownedCount = board.clearContents()
        ownedText = text
        guard board.changeCount == ownedCount else {
            ownedCount = nil
            throw WindowEventError.unavailable("clipboard changed after preparation; newer copy left intact")
        }
        guard board.writeObjects([item]) else {
            _ = restoreLocked()
            throw WindowEventError.unavailable("clipboard write failed; paste not dispatched")
        }
        ownedCount = board.changeCount
    }

    public func dispatchPaste(_ primitive: () throws -> Void) throws {
        lock.lock()
        let expected = ownedCount
        let current = board.changeCount
        lock.unlock()
        guard let expected, current == expected else {
            throw WindowEventError.unavailable("clipboard ownership changed before paste; no shortcut dispatched")
        }
        try primitive()
    }

    /// Puts the original items back. A moved change count normally means a newer copy that must
    /// be left alone, but a clipboard-history app can re-publish the item it just recorded, which
    /// also moves the count. While the board still carries exactly our text and nothing else, the
    /// user copied nothing new, so the original is restored rather than lost.
    /// Best effort: AppKit has no atomic compare-and-swap.
    @discardableResult public func restore() -> String {
        lock.lock()
        defer { lock.unlock() }
        return restoreLocked()
    }

    private func restoreLocked() -> String {
        guard let expected = ownedCount else { return "unchanged" }
        let ours = ownedText
        ownedCount = nil
        ownedText = nil
        func stillOurs() -> Bool {
            if board.changeCount == expected { return true }
            guard let ours, let items = board.pasteboardItems, items.count == 1 else { return false }
            return items[0].string(forType: .string) == ours
        }
        guard stillOurs() else { return "skipped-concurrent-change" }
        let items = original.map { values in
            let item = NSPasteboardItem()
            for (type, data) in values { item.setData(data, forType: type) }
            return item
        }
        guard stillOurs() else { return "skipped-concurrent-change" }
        let cleared = board.clearContents()
        guard board.changeCount == cleared else { return "skipped-concurrent-change" }
        return items.isEmpty || board.writeObjects(items) ? "restored" : "restore-failed"
    }
}
