// The artifact component kit. Import from any served/built artifact:
//   import { Page, Hero, Tabs, Section, MdViewer, Timeline, Simulator } from "@artifact/kit";

export { type ChartConfiguration, ChartJs, type ChartJsProps } from "./chartjs";
export {
    type ChartMarker,
    type ChartSeries,
    DayChart,
    type DayChartProps,
    DonutChart,
    type DonutChartProps,
    type DonutSlice,
    TONE_COLOR,
} from "./charts";
export {
    Bullets,
    type BulletsProps,
    DataTable,
    type DataTableCell,
    type DataTableColumn,
    type DataTableProps,
    QA,
    type QaItem,
    type QaProps,
    SeriesTable,
    type SeriesTableProps,
    type TabItem,
    Tabs,
    type TabsProps,
    Timeline,
    type TimelineEntry,
    type TimelineProps,
} from "./data";
export {
    MD_BODY_CLASS,
    Md,
    MdInline,
    type MdProps,
    MdViewer,
    type MdViewerProps,
    renderMarkdown,
    renderMarkdownInline,
} from "./md";
export {
    Badge,
    type BadgeProps,
    type BodyContent,
    Callout,
    type CalloutProps,
    Card,
    CardGrid,
    type CardGridProps,
    type CardProps,
    type ChipItem,
    Chips,
    type ChipsProps,
    Claim,
    type ClaimProps,
    CodeBlock,
    type CodeBlockProps,
    Collapse,
    type CollapseProps,
    FileMark,
    type FileMarkProps,
    Hero,
    type HeroProps,
    Note,
    type NoteProps,
    Page,
    type PageProps,
    Quote,
    type QuoteProps,
    renderBody,
    Section,
    type SectionProps,
    SegmentedControl,
    type SegmentedControlProps,
    type SegmentedOption,
    StatGrid,
    type StatGridProps,
    type StatItem,
    Superseded,
    type SupersededProps,
    TONE_BG,
    TONE_BORDER,
    TONE_DOT,
    TONE_TEXT,
    type Tone,
} from "./primitives";
export {
    matchRoute,
    type RouteDef,
    Router,
    RouterLink,
    type RouterLinkProps,
    type RouterProps,
    useNavigate,
    useParams,
    useRoutePath,
} from "./router";
export {
    ParametricSimulator,
    type ParametricSimulatorProps,
    type SimControl,
    type SimParams,
    type SimPreset,
    type SimStep,
    Simulator,
    type SimulatorProps,
    type SimValue,
} from "./simulator";
