// The artifact component kit. Import from any served/built artifact:
//   import { Page, Hero, Tabs, Section, MdViewer, Timeline, Simulator } from "@artifact/kit";

export { type ChartConfiguration, ChartJs, type ChartJsProps } from "./chartjs";
export {
    type ChartMarker,
    type ChartSeries,
    DayChart,
    type DayChartProps,
    DonutChart,
    type DonutChartProps,
    type DonutSlice,
    TONE_COLOR,
} from "./charts";
export {
    Bullets,
    type BulletsProps,
    DataTable,
    type DataTableCell,
    type DataTableColumn,
    type DataTableProps,
    QA,
    type QaItem,
    type QaProps,
    SeriesTable,
    type SeriesTableProps,
    type TabItem,
    Tabs,
    type TabsProps,
    Timeline,
    type TimelineEntry,
    type TimelineProps,
} from "./data";
export { Mermaid, type MermaidProps, ZoomPane, type ZoomPaneProps } from "./diagrams";
export {
    type DiffFile,
    type DiffHunk,
    type DiffRow,
    type DiffRowKind,
    type DiffSplitRow,
    DiffView,
    type DiffViewProps,
    diffFileFromPatch,
    pairDiffRows,
} from "./diff";
export {
    MD_BODY_CLASS,
    Md,
    MdInline,
    type MdProps,
    MdViewer,
    type MdViewerProps,
    renderMarkdown,
    renderMarkdownInline,
} from "./md";
export {
    configureMermaid,
    hydrateMermaidFences,
    loadMermaid,
    MERMAID_ESM_URL,
    type MermaidApi,
    type MermaidRenderResult,
    type MermaidSource,
    renderMermaidSvg,
} from "./mermaid-core";
export {
    Badge,
    type BadgeProps,
    type BodyContent,
    Callout,
    type CalloutProps,
    Card,
    CardGrid,
    type CardGridProps,
    type CardProps,
    type ChipItem,
    Chips,
    type ChipsProps,
    Claim,
    type ClaimProps,
    CodeBlock,
    type CodeBlockProps,
    Collapse,
    type CollapseProps,
    FileMark,
    type FileMarkProps,
    Hero,
    type HeroProps,
    Note,
    type NoteProps,
    Page,
    type PageProps,
    Quote,
    type QuoteProps,
    renderBody,
    Section,
    type SectionProps,
    SegmentedControl,
    type SegmentedControlProps,
    type SegmentedOption,
    StatGrid,
    type StatGridProps,
    type StatItem,
    Superseded,
    type SupersededProps,
    TONE_BG,
    TONE_BORDER,
    TONE_DOT,
    TONE_TEXT,
    type Tone,
} from "./primitives";
export {
    matchRoute,
    type RouteDef,
    Router,
    RouterLink,
    type RouterLinkProps,
    type RouterProps,
    useNavigate,
    useParams,
    useRoutePath,
} from "./router";
export {
    ParametricSimulator,
    type ParametricSimulatorProps,
    type SimControl,
    type SimParams,
    type SimPreset,
    type SimStep,
    Simulator,
    type SimulatorProps,
    type SimValue,
} from "./simulator";
export {
    Compare,
    type CompareItem,
    type CompareProps,
    Figure,
    type FigureProps,
    JsonView,
    type JsonViewProps,
    KeyValue,
    type KeyValueItem,
    type KeyValueProps,
    STEP_TONE,
    type StepItem,
    type StepStatus,
    Steps,
    type StepsProps,
    type TreeNode,
    type TreePath,
    TreeView,
    type TreeViewProps,
    treeFromPaths,
} from "./structure";
export {
    Heatmap,
    type HeatmapProps,
    heatShare,
    Meter,
    type MeterProps,
    type MeterThresholds,
    meterTone,
    Sparkline,
    type SparklineProps,
    sparklinePath,
} from "./viz";
