/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as TopRouteImport } from './routes/top'
import { Route as TogetherRouteImport } from './routes/together'
import { Route as TimeRouteImport } from './routes/time'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as BiographyRouteImport } from './routes/biography'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProfilesRouteImport } from './routes/api/profiles'
import { Route as ApiReportNameRouteImport } from './routes/api/report.$name'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const TogetherRoute = TogetherRouteImport.update({
  id: '/together',
  path: '/together',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const BiographyRoute = BiographyRouteImport.update({
  id: '/biography',
  path: '/biography',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesRoute = ApiProfilesRouteImport.update({
  id: '/api/profiles',
  path: '/api/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportNameRoute = ApiReportNameRouteImport.update({
  id: '/api/report/$name',
  path: '/api/report/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/dna': typeof DnaRoute
  '/explore': typeof ExploreRoute
  '/habits': typeof HabitsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/time': typeof TimeRoute
  '/together': typeof TogetherRoute
  '/top': typeof TopRoute
  '/wrapped': typeof WrappedRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/report/$name': typeof ApiReportNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/dna': typeof DnaRoute
  '/explore': typeof ExploreRoute
  '/habits': typeof HabitsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/time': typeof TimeRoute
  '/together': typeof TogetherRoute
  '/top': typeof TopRoute
  '/wrapped': typeof WrappedRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/report/$name': typeof ApiReportNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/dna': typeof DnaRoute
  '/explore': typeof ExploreRoute
  '/habits': typeof HabitsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/time': typeof TimeRoute
  '/together': typeof TogetherRoute
  '/top': typeof TopRoute
  '/wrapped': typeof WrappedRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/report/$name': typeof ApiReportNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biography'
    | '/dna'
    | '/explore'
    | '/habits'
    | '/library'
    | '/settings'
    | '/time'
    | '/together'
    | '/top'
    | '/wrapped'
    | '/api/profiles'
    | '/api/report/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biography'
    | '/dna'
    | '/explore'
    | '/habits'
    | '/library'
    | '/settings'
    | '/time'
    | '/together'
    | '/top'
    | '/wrapped'
    | '/api/profiles'
    | '/api/report/$name'
  id:
    | '__root__'
    | '/'
    | '/biography'
    | '/dna'
    | '/explore'
    | '/habits'
    | '/library'
    | '/settings'
    | '/time'
    | '/together'
    | '/top'
    | '/wrapped'
    | '/api/profiles'
    | '/api/report/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiographyRoute: typeof BiographyRoute
  DnaRoute: typeof DnaRoute
  ExploreRoute: typeof ExploreRoute
  HabitsRoute: typeof HabitsRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  TimeRoute: typeof TimeRoute
  TogetherRoute: typeof TogetherRoute
  TopRoute: typeof TopRoute
  WrappedRoute: typeof WrappedRoute
  ApiProfilesRoute: typeof ApiProfilesRoute
  ApiReportNameRoute: typeof ApiReportNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/together': {
      id: '/together'
      path: '/together'
      fullPath: '/together'
      preLoaderRoute: typeof TogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biography': {
      id: '/biography'
      path: '/biography'
      fullPath: '/biography'
      preLoaderRoute: typeof BiographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles': {
      id: '/api/profiles'
      path: '/api/profiles'
      fullPath: '/api/profiles'
      preLoaderRoute: typeof ApiProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report/$name': {
      id: '/api/report/$name'
      path: '/api/report/$name'
      fullPath: '/api/report/$name'
      preLoaderRoute: typeof ApiReportNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiographyRoute: BiographyRoute,
  DnaRoute: DnaRoute,
  ExploreRoute: ExploreRoute,
  HabitsRoute: HabitsRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  TimeRoute: TimeRoute,
  TogetherRoute: TogetherRoute,
  TopRoute: TopRoute,
  WrappedRoute: WrappedRoute,
  ApiProfilesRoute: ApiProfilesRoute,
  ApiReportNameRoute: ApiReportNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
