import { existsSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { discoverTools } from "@app/tools/lib/discovery";
import * as p from "@clack/prompts";
import { getAgentRuntimeContext } from "@genesiscz/utils/agent-runtime";
import { runTool } from "@genesiscz/utils/cli";
import { env } from "@genesiscz/utils/env";
import { SafeJSON } from "@genesiscz/utils/json";
import { logger, out } from "@genesiscz/utils/logger";
import { Command } from "commander";
import pc from "picocolors";

const MARKETPLACE_NAME = "genesis-tools";
/** Only used when this process cannot find a real checkout to point the marketplace at. */
const MARKETPLACE_FALLBACK_SOURCE = "https://github.com/genesiscz/GenesisTools";
const PLUGIN_REF = "genesis-tools@genesis-tools";

interface MarketplaceEntry {
    name?: string;
    /** "directory" | "git" | "github" */
    source?: string;
    /** Present for directory sources. */
    path?: string;
}

async function runClaude(args: string[]): Promise<number> {
    return Bun.spawn(["claude", ...args], { stdio: ["inherit", "inherit", "inherit"] }).exited;
}

/** Run a `claude … --json` query and parse it; null on non-zero exit or unparseable output. */
async function claudeJson<T>(args: string[]): Promise<T | null> {
    const proc = Bun.spawn(["claude", ...args], { stdio: ["ignore", "pipe", "ignore"] });
    const stdout = await new Response(proc.stdout).text();

    if ((await proc.exited) !== 0) {
        return null;
    }

    try {
        return SafeJSON.parse(stdout) as T;
    } catch (err) {
        logger.debug({ err, args }, "update: could not parse claude CLI --json output");
        return null;
    }
}

async function findMarketplace(name: string): Promise<MarketplaceEntry | null> {
    const entries = await claudeJson<MarketplaceEntry[]>(["plugin", "marketplace", "list", "--json"]);

    if (!Array.isArray(entries)) {
        return null;
    }

    return entries.find((entry) => entry.name === name) ?? null;
}

async function pluginIsInstalled(id: string): Promise<boolean> {
    const entries = await claudeJson<Array<{ id?: string }>>(["plugin", "list", "--json"]);

    return Array.isArray(entries) && entries.some((entry) => entry.id === id);
}

const program = new Command()
    .name("update")
    .description("Update GenesisTools to the latest version")
    .action(async () => {
        const genesisPath = env.tools.getPath() || resolve(import.meta.dir, "../..");
        const srcDir = join(genesisPath, "src");

        out.println(pc.cyan("\n  Updating GenesisTools...\n"));

        // 1. Git pull (discard bun.lock changes — it will be regenerated by bun install)
        out.println(pc.dim("  Pulling latest changes..."));
        await Bun.spawn(["git", "checkout", "--", "bun.lock"], {
            cwd: genesisPath,
            stdio: ["inherit", "inherit", "inherit"],
        }).exited;
        const pull = Bun.spawn(["git", "pull"], {
            cwd: genesisPath,
            stdio: ["inherit", "inherit", "inherit"],
        });
        if ((await pull.exited) !== 0) {
            out.error(pc.red("  Failed to git pull"));
            process.exit(1);
        }

        // 2. Install dependencies (clean retry if first attempt fails)
        out.println(pc.dim("\n  Installing dependencies..."));
        const install = Bun.spawn(["bun", "install"], {
            cwd: genesisPath,
            stdio: ["inherit", "inherit", "inherit"],
        });

        if ((await install.exited) !== 0) {
            out.println(pc.yellow("  Install failed, retrying with clean node_modules..."));
            rmSync(join(genesisPath, "node_modules"), { recursive: true, force: true });
            const retry = Bun.spawn(["bun", "install"], {
                cwd: genesisPath,
                stdio: ["inherit", "inherit", "inherit"],
            });

            if ((await retry.exited) !== 0) {
                out.error(pc.red("  Failed to install dependencies"));
                process.exit(1);
            }
        }

        // 3. Claude Code plugin management
        const inClaudeCode = getAgentRuntimeContext().isInAgent;
        const runClaudeUpdates = await p.confirm({
            message: inClaudeCode
                ? "Run Claude plugin update and marketplace update?"
                : "Run Claude marketplace update, add, and plugin install?",
            initialValue: true,
        });
        if (p.isCancel(runClaudeUpdates)) {
            p.cancel("Cancelled");
            process.exit(0);
        }
        if (runClaudeUpdates) {
            // This checkout IS the marketplace — step 1 just pulled it. Registering the GitHub
            // URL instead makes Claude Code clone a SECOND copy into
            // ~/.claude/plugins/marketplaces/genesis-tools and read the plugin from there, so
            // edits in this repo stop taking effect until they are committed AND pushed.
            const checkout = resolve(genesisPath);
            const isCheckout = existsSync(join(checkout, ".claude-plugin", "marketplace.json"));
            const existing = await findMarketplace(MARKETPLACE_NAME);
            const pointsAtCheckout =
                existing?.source === "directory" && existing.path !== undefined && resolve(existing.path) === checkout;

            // True when we re-source an ALREADY-registered marketplace (the git-clone → this-repo
            // flip), as opposed to registering it for the first time.
            let repointed = false;

            if (isCheckout && !pointsAtCheckout) {
                // `marketplace add` OVERWRITES an existing registration's source rather than
                // refusing, so this one command covers both first registration and the flip.
                out.println(
                    pc.dim(existing ? `\n  Re-pointing marketplace at ${checkout}...` : "\n  Adding marketplace...")
                );
                await runClaude(["plugin", "marketplace", "add", checkout]);
                repointed = existing !== null;
            } else if (!isCheckout && !existing) {
                out.println(pc.yellow(`\n  ${checkout} is not a GenesisTools checkout; using the GitHub marketplace.`));
                await runClaude(["plugin", "marketplace", "add", MARKETPLACE_FALLBACK_SOURCE]);
            } else {
                out.println(pc.dim("\n  Refreshing marketplace..."));
            }

            // Claude Code caches each marketplace's PARSED plugin catalog; even a directory
            // source is not re-read on its own. Skipping this is what makes the next step fail
            // with `Plugin "genesis-tools" not found in marketplace "genesis-tools"`.
            await runClaude(["plugin", "marketplace", "update", MARKETPLACE_NAME]);

            if (!(await pluginIsInstalled(PLUGIN_REF))) {
                out.println(pc.dim("\n  Installing plugin..."));

                if ((await runClaude(["plugin", "install", PLUGIN_REF])) !== 0) {
                    out.println(pc.yellow("  Plugin install had issues"));
                }
            } else if (repointed) {
                // The installed copy was taken from the OLD source, and the plugin cache is keyed
                // by version — so `plugin update` is a no-op whenever the version is unchanged and
                // the stale copy would survive the flip. Reinstall to re-copy from this checkout.
                out.println(pc.dim("\n  Reinstalling plugin from this checkout..."));
                await runClaude(["plugin", "uninstall", PLUGIN_REF, "--keep-data", "-y"]);

                if ((await runClaude(["plugin", "install", PLUGIN_REF])) !== 0) {
                    out.println(pc.yellow("  Plugin reinstall had issues"));
                }
            } else {
                out.println(pc.dim("\n  Updating Claude Code plugin..."));

                if ((await runClaude(["plugin", "update", PLUGIN_REF])) !== 0) {
                    out.println(pc.yellow("  Plugin update had issues"));
                }
            }

            if (inClaudeCode) {
                out.println(pc.dim("\n  Restart Claude Code to apply the new plugin version."));
            }
        }

        // 4. Show latest changelog entry
        const changelogPath = join(genesisPath, "CHANGELOG.md");
        if (existsSync(changelogPath)) {
            const changelog = readFileSync(changelogPath, "utf-8");
            const latestEntry = extractLatestEntry(changelog);
            if (latestEntry) {
                out.println(pc.cyan("\n  Latest changes:"));
                out.println(pc.dim(`  ${latestEntry.split("\n").join("\n  ")}`));
            }
        }

        // 5. "Did you know" message
        const tools = discoverTools(srcDir);
        const skills = discoverSkills(join(genesisPath, "plugins/genesis-tools/skills"));

        out.println(pc.green("\n  GenesisTools updated successfully!\n"));
        out.println(pc.cyan("  Did you know we have a lot of Claude tools available? Install with:\n"));
        out.println("    claude plugin marketplace add https://github.com/genesiscz/GenesisTools");
        out.println("    claude plugin install genesis-tools@genesis-tools\n");

        out.println(pc.cyan("  Available commands:"));
        for (const tool of tools.slice(0, 20)) {
            out.println(`    ${pc.bold(tool.name)} - ${pc.dim(tool.description)}`);
        }
        if (tools.length > 20) {
            out.println(pc.dim(`    ... and ${tools.length - 20} more. Run 'tools' to see all.`));
        }

        out.println(pc.cyan("\n  Available skills:"));
        for (const skill of skills) {
            out.println(`    ${pc.bold(`gt:${skill.name}`)} - ${pc.dim(skill.description)}`);
        }

        out.println("");
    });

function extractLatestEntry(changelog: string): string | null {
    const lines = changelog.split("\n");
    let start = -1;
    let end = lines.length;
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].startsWith("## ") && start === -1) {
            start = i;
        } else if (lines[i].startsWith("## ") && start !== -1) {
            end = i;
            break;
        }
    }
    if (start === -1) {
        return null;
    }
    return lines.slice(start, end).join("\n").trim();
}

function discoverSkills(skillsDir: string): Array<{ name: string; description: string }> {
    if (!existsSync(skillsDir)) {
        return [];
    }
    const skills: Array<{ name: string; description: string }> = [];
    for (const entry of readdirSync(skillsDir)) {
        const skillFile = join(skillsDir, entry, "SKILL.md");
        if (existsSync(skillFile)) {
            const content = readFileSync(skillFile, "utf-8");
            const descMatch = content.match(/^description:\s*(.+)$/m);
            skills.push({
                name: entry,
                description: descMatch?.[1]?.trim() ?? entry,
            });
        }
    }
    return skills.sort((a, b) => a.name.localeCompare(b.name));
}

await runTool(program, { tool: "update" });
