import { existsSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { genesisToolsMcpRegistration, installGenesisToolsMcp } from "@app/genesis-tools-mcp/lib/mcp-install";
import { appStatus, buildApp } from "@app/macos/lib/permissions/app";
import { discoverTools } from "@app/tools/lib/discovery";
import * as p from "@clack/prompts";
import { getAgentRuntimeContext } from "@genesiscz/utils/agent/runtime";
import { execTool, execToolInteractive, isInteractive, isVerbose, runTool, suggestCommand } from "@genesiscz/utils/cli";
import { toolCommand } from "@genesiscz/utils/cli/tool-command";
import { env } from "@genesiscz/utils/env";
import { SafeJSON } from "@genesiscz/utils/json";
import { logger, out } from "@genesiscz/utils/logger";
import { genesisAppBuildHint } from "@genesiscz/utils/macos/xcode";
import { Command } from "commander";
import pc from "picocolors";
import { printUpdateCatalogue } from "./diff";
import { genesisAppRefreshAction } from "./genesis-app-refresh";
import {
    MARKETPLACE_FALLBACK_SOURCE,
    MARKETPLACE_NAME,
    type MarketplaceEntry,
    type MarketplaceLookup,
    PLUGIN_REF,
    planMarketplaceAction,
} from "./marketplace";
import { offerMcpRegistration } from "./mcp-registration-offer";
import { recoverFromFailedPull } from "./recovery";

/** Bun.spawn throws SYNCHRONOUSLY when the executable is missing, so a bare await never sees it. */
async function runClaude(args: string[]): Promise<number> {
    try {
        return await Bun.spawn(["claude", ...args], { stdio: ["inherit", "inherit", "inherit"] }).exited;
    } catch (err) {
        logger.warn({ err, args }, "update: could not run the claude CLI");
        return 127;
    }
}

/** Run a `claude … --json` query and parse it; null on spawn failure, non-zero exit or bad output. */
async function claudeJson<T>(args: string[]): Promise<T | null> {
    let stdout: string;
    let exitCode: number;

    try {
        const proc = Bun.spawn(["claude", ...args], { stdio: ["ignore", "pipe", "ignore"] });
        stdout = await new Response(proc.stdout).text();
        exitCode = await proc.exited;
    } catch (err) {
        logger.warn({ err, args }, "update: could not run the claude CLI");
        return null;
    }

    if (exitCode !== 0) {
        logger.debug({ args, exitCode }, "update: claude CLI --json query exited non-zero");
        return null;
    }

    try {
        // Subprocess output is a machine boundary, not a hand-written config: no comment tolerance.
        return SafeJSON.parse(stdout, { strict: true }) as T;
    } catch (err) {
        logger.debug({ err, args }, "update: could not parse claude CLI --json output");
        return null;
    }
}

async function lookupMarketplace(name: string): Promise<MarketplaceLookup> {
    const entries = await claudeJson<MarketplaceEntry[]>(["plugin", "marketplace", "list", "--json"]);

    if (!Array.isArray(entries)) {
        return { status: "unknown" };
    }

    const entry = entries.find((candidate) => candidate.name === name);

    return entry ? { status: "found", entry } : { status: "absent" };
}

async function pluginIsInstalled(id: string): Promise<boolean> {
    const entries = await claudeJson<Array<{ id?: string }>>(["plugin", "list", "--json"]);

    return Array.isArray(entries) && entries.some((entry) => entry.id === id);
}

const program = new Command()
    .name("update")
    .description("Update GenesisTools to the latest version")
    .action(async () => {
        const genesisPath = env.tools.getPath() || resolve(import.meta.dir, "../..");
        const srcDir = join(genesisPath, "src");

        out.println(pc.cyan("\n  Updating GenesisTools...\n"));

        // 1. Git pull (discard bun.lock changes — it will be regenerated by bun install)
        out.println(pc.dim("  Pulling latest changes..."));
        await Bun.spawn(["git", "checkout", "--", "bun.lock"], {
            cwd: genesisPath,
            stdio: ["inherit", "inherit", "inherit"],
        }).exited;
        const pull = Bun.spawn(["git", "pull"], {
            cwd: genesisPath,
            stdio: ["inherit", "inherit", "inherit"],
        });
        if ((await pull.exited) !== 0) {
            out.println(pc.yellow("\n  git pull failed — trying to recover without losing local work..."));

            if (!(await recoverFromFailedPull(genesisPath))) {
                out.error(pc.red("\n  Could not update automatically."));
                out.println(pc.dim("  Recover by hand (this discards local changes, so stash first):"));
                out.println(pc.dim(`    cd ${genesisPath}`));
                out.println(pc.dim("    git stash push --include-untracked -m 'pre-update'"));
                out.println(pc.dim("    git fetch origin && git reset --hard origin/master"));
                out.println(pc.dim("  If that still fails, re-clone the repository."));
                process.exit(1);
            }
        }

        // 2. Install dependencies (clean retry if first attempt fails)
        out.println(pc.dim("\n  Installing dependencies..."));
        const install = Bun.spawn(["bun", "install"], {
            cwd: genesisPath,
            stdio: ["inherit", "inherit", "inherit"],
        });

        if ((await install.exited) !== 0) {
            out.println(pc.yellow("  Install failed, retrying with clean node_modules..."));
            rmSync(join(genesisPath, "node_modules"), { recursive: true, force: true });
            const retry = Bun.spawn(["bun", "install"], {
                cwd: genesisPath,
                stdio: ["inherit", "inherit", "inherit"],
            });

            if ((await retry.exited) !== 0) {
                out.error(pc.red("  Failed to install dependencies"));
                process.exit(1);
            }
        }

        // 3. Install or rebuild GenesisTools.app.
        //
        // The bundle lives outside the repo (~/Applications), so a pull never touches it and the
        // existing user would never get the app at all, and after a source change the old launcher
        // would keep running while the repo moved on. Grants survive either way, because re-signing
        // keeps the identity. Rebuilding while this very process runs under the old bundle is safe:
        // the running binary stays mapped until it exits.
        await refreshGenesisApp();

        // 3b. Long-running servers (daemons, gateways, dashboards) keep the code they started with.
        await offerServiceRestarts();

        // 4. Claude Code plugin management
        const inClaudeCode = getAgentRuntimeContext().isInAgent;
        const runClaudeUpdates = await p.confirm({
            message: inClaudeCode
                ? "Run Claude plugin update and marketplace update?"
                : "Run Claude marketplace update, add, and plugin install?",
            initialValue: true,
        });
        if (p.isCancel(runClaudeUpdates)) {
            p.cancel("Cancelled");
            process.exit(0);
        }
        if (runClaudeUpdates) {
            // This checkout IS the marketplace — step 1 just pulled it. Registering the GitHub
            // URL instead makes Claude Code clone a SECOND copy into
            // ~/.claude/plugins/marketplaces/genesis-tools and read the plugin from there, so
            // edits in this repo stop taking effect until they are committed AND pushed.
            const checkout = resolve(genesisPath);
            const isCheckout = existsSync(join(checkout, ".claude-plugin", "marketplace.json"));
            const lookup: MarketplaceLookup = await lookupMarketplace(MARKETPLACE_NAME);
            const plan = planMarketplaceAction({ isCheckout, checkout, lookup, resolvePath: resolve });

            if (plan.reason) {
                out.println(pc.yellow(`\n  ${plan.reason}`));
            }

            // Every step below is a prerequisite of the next one. A failure that is only printed
            // and then stepped over is how `tools update` used to uninstall a working plugin and
            // then fail to reinstall it, leaving the user with nothing.
            let marketplaceReady = true;

            if (plan.action === "add-checkout") {
                // `marketplace add` OVERWRITES an existing registration's source rather than
                // refusing, so this one command covers both first registration and the flip.
                out.println(
                    pc.dim(
                        plan.repointed ? `\n  Re-pointing marketplace at ${checkout}...` : "\n  Adding marketplace..."
                    )
                );
                marketplaceReady = (await runClaude(["plugin", "marketplace", "add", checkout])) === 0;
            } else if (plan.action === "add-fallback") {
                out.println(pc.yellow(`\n  ${checkout} is not a GenesisTools checkout; using the GitHub marketplace.`));
                marketplaceReady =
                    (await runClaude(["plugin", "marketplace", "add", MARKETPLACE_FALLBACK_SOURCE])) === 0;
            } else {
                out.println(pc.dim("\n  Refreshing marketplace..."));
            }

            if (!marketplaceReady) {
                out.error(pc.red("  Marketplace registration failed — leaving the installed plugin untouched."));
            } else {
                // Claude Code caches each marketplace's PARSED plugin catalog; even a directory
                // source is not re-read on its own. Skipping this is what makes the next step fail
                // with `Plugin "genesis-tools" not found in marketplace "genesis-tools"`.
                if ((await runClaude(["plugin", "marketplace", "update", MARKETPLACE_NAME])) !== 0) {
                    out.error(pc.red("  Marketplace refresh failed — leaving the installed plugin untouched."));
                } else if (!(await pluginIsInstalled(PLUGIN_REF))) {
                    out.println(pc.dim("\n  Installing plugin..."));

                    if ((await runClaude(["plugin", "install", PLUGIN_REF])) !== 0) {
                        out.println(pc.yellow("  Plugin install had issues"));
                    }
                } else if (plan.repointed) {
                    // The installed copy was taken from the OLD source, and the plugin cache is keyed
                    // by version — so `plugin update` is a no-op whenever the version is unchanged and
                    // the stale copy would survive the flip. Reinstall to re-copy from this checkout.
                    out.println(pc.dim("\n  Reinstalling plugin from this checkout..."));

                    if ((await runClaude(["plugin", "uninstall", PLUGIN_REF, "--keep-data", "-y"])) !== 0) {
                        out.println(pc.yellow("  Plugin uninstall failed — keeping the currently installed copy."));
                    } else if ((await runClaude(["plugin", "install", PLUGIN_REF])) !== 0) {
                        out.error(
                            pc.red(
                                `  Plugin reinstall failed after uninstall. Restore it with: ` +
                                    `claude plugin install ${PLUGIN_REF}`
                            )
                        );
                    }
                } else {
                    out.println(pc.dim("\n  Updating Claude Code plugin..."));

                    if ((await runClaude(["plugin", "update", PLUGIN_REF])) !== 0) {
                        out.println(pc.yellow("  Plugin update had issues"));
                    }
                }
            }

            if (inClaudeCode) {
                out.println(pc.dim("\n  Restart Claude Code to apply the new plugin version."));
            }
        }

        // 4b. The genesis-tools MCP server (D4, round 2): registration stays manual, but a TTY
        // gets asked once it notices the server is missing.
        await offerGenesisToolsMcpRegistration();

        // 5. Show latest changelog entry (full text only with --verbose; the version line in
        // the short summary below already says when it moved).
        const changelogPath = join(genesisPath, "CHANGELOG.md");
        let latestVersionHeading: string | null = null;
        if (existsSync(changelogPath)) {
            const changelog = readFileSync(changelogPath, "utf-8");
            const latestEntry = extractLatestEntry(changelog);
            if (latestEntry) {
                latestVersionHeading =
                    latestEntry
                        .split("\n")[0]
                        ?.replace(/^##\s*/, "")
                        .trim() ?? null;

                if (isVerbose()) {
                    out.println(pc.cyan("\n  Latest changes:"));
                    out.println(pc.dim(`  ${latestEntry.split("\n").join("\n  ")}`));
                }
            }
        }

        // 6. Catalogue summary: only what changed since the last run (D4, round 2 — the full
        // dump every run was unreadable noise). `--verbose` prints the full lists instead.
        const tools = discoverTools(srcDir);
        const skills = discoverSkills(join(genesisPath, "plugins/genesis-tools/skills"));

        out.println(pc.green("\n  GenesisTools updated successfully!\n"));

        printUpdateCatalogue({
            current: {
                version: latestVersionHeading,
                tools: tools.map((t) => ({ name: t.name, description: t.description })),
                skills: skills.map((s) => ({ name: s.name, description: s.description })),
            },
            verbose: isVerbose(),
            println: (line) => out.println(line),
        });

        out.println("");
    });

/**
 * Install GenesisTools.app when it is missing, or re-sign it when its sources moved.
 *
 * Never fatal: an update that cannot build the app is still a successful update, tools keep
 * running under the terminal's own permissions, and `tools macos permissions` reports the gap.
 */
/**
 * Offers to restart the servers still on the code from before this update. Both steps run
 * `tools services` as a child, so the freshly pulled code does the work, not the copy this update
 * process loaded before the pull. Agent sessions are never listed there.
 */
async function offerServiceRestarts(): Promise<void> {
    const listed = await execTool(["services", "list", "--json"]);

    if (listed.exitCode !== 0) {
        logger.warn({ stderr: listed.stderr }, "update: could not list services");
        return;
    }

    let stale = 0;

    try {
        const rows: unknown = SafeJSON.parse(listed.stdout, { strict: true });
        stale = Array.isArray(rows)
            ? rows.filter((row) => Array.isArray(row?.stale) && row.stale.length > 0).length
            : 0;
    } catch (error) {
        logger.warn({ error }, `update: ${toolCommand("services")} printed no JSON`);
        return;
    }

    if (stale === 0) {
        return;
    }

    const command = suggestCommand("tools services", { replaceCommand: ["restart", "--stale"] });

    if (!isInteractive()) {
        out.println(pc.yellow(`\n  ${stale} service(s) run code from before this update: ${command}`));
        return;
    }

    out.println(pc.dim(`\n  ${stale} service(s) run code from before this update.`));
    // A restart interrupts whoever uses the server, so it is asked for, default no. `restart --stale`
    // itself picks the stale rows without a prompt, so this confirm is the only one.
    const restart = await p.confirm({ message: `Restart the ${stale} stale service(s) now?`, initialValue: false });

    if (p.isCancel(restart) || !restart) {
        out.println(pc.dim(`  Later: ${command}`));
        return;
    }

    await execToolInteractive(["services", "restart", "--stale"]);
}

/**
 * Keeps an already-installed GenesisTools.app current. #445 made the FIRST build opt-in
 * (`install.sh` asks, this command never did): someone who answered "no", or who runs an
 * old `install.sh` that predates the app, must not have it installed behind their back by a
 * routine update.
 */
async function refreshGenesisApp(): Promise<void> {
    if (process.platform !== "darwin") {
        return;
    }

    const status = appStatus();

    if (genesisAppRefreshAction(status) === "skip") {
        return;
    }

    out.println(pc.dim("\n  Rebuilding GenesisTools.app (its sources changed in this update)..."));

    try {
        const result = await buildApp({ onStep: (message) => out.println(pc.dim(`    ${message}`)) });

        out.println(
            pc.green(
                `  GenesisTools.app rebuilt${result.signature.adhoc ? " (ad-hoc signed — macOS will forget its privacy grants)" : "; privacy grants survive, the signing identity is unchanged"}.`
            )
        );
    } catch (err) {
        logger.warn({ err }, "update: GenesisTools.app rebuild failed");
        out.println(
            pc.yellow(`  Could not rebuild GenesisTools.app: ${err instanceof Error ? err.message : String(err)}`)
        );
        out.println(pc.dim(`  Tools keep running under the previous bundle. ${genesisAppBuildHint()}`));
    }
}

/**
 * D4, round 2: registration stays manual (never automatic), but `tools update` is where we ask.
 * `genesisToolsMcpRegistration` is read-only; the confirm below is the only place that mutates.
 */
async function offerGenesisToolsMcpRegistration(): Promise<void> {
    await offerMcpRegistration({
        registration: genesisToolsMcpRegistration,
        isTty: isInteractive,
        confirmRegister: async () => {
            const answer = await p.confirm({
                message: "Register the genesis-tools MCP server with Claude Code now?",
                initialValue: false,
            });
            return answer === true;
        },
        register: () => installGenesisToolsMcp(),
        log: (message) => out.println(pc.dim(`\n  ${message}`)),
    });
}

function extractLatestEntry(changelog: string): string | null {
    const lines = changelog.split("\n");
    let start = -1;
    let end = lines.length;
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].startsWith("## ") && start === -1) {
            start = i;
        } else if (lines[i].startsWith("## ") && start !== -1) {
            end = i;
            break;
        }
    }
    if (start === -1) {
        return null;
    }
    return lines.slice(start, end).join("\n").trim();
}

function discoverSkills(skillsDir: string): Array<{ name: string; description: string }> {
    if (!existsSync(skillsDir)) {
        return [];
    }
    const skills: Array<{ name: string; description: string }> = [];
    for (const entry of readdirSync(skillsDir)) {
        const skillFile = join(skillsDir, entry, "SKILL.md");
        if (existsSync(skillFile)) {
            const content = readFileSync(skillFile, "utf-8");
            const descMatch = content.match(/^description:\s*(.+)$/m);
            skills.push({
                name: entry,
                description: descMatch?.[1]?.trim() ?? entry,
            });
        }
    }
    return skills.sort((a, b) => a.name.localeCompare(b.name));
}

await runTool(program, { tool: "update" });
