import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { SafeJSON } from "@genesiscz/utils/json";
import { logger } from "@genesiscz/utils/logger";
import { REPO_ROOT, RUNTIME_DIR } from "./vite";

/**
 * Agent/editor DX without a folder scaffold:
 * - `kitApiDts()` emits the kit's full typed API (one .d.ts text) so an agent
 *   can author against the kit without ever reading component source.
 * - `writeEditorTsconfig()` drops ONE optional tsconfig.json into an artifact
 *   dir so a human editor resolves `@artifact/kit`, repo imports, and react —
 *   the runtime never needs it.
 */

const KIT_DIR = join(RUNTIME_DIR, "kit");
const KIT_FILES = ["primitives.tsx", "data.tsx", "md.tsx", "simulator.tsx", "router.tsx", "index.ts"];

function kitStamp(): string {
    return KIT_FILES.map((f) => `${f}:${statSync(join(KIT_DIR, f)).mtimeMs}`).join("|");
}

/** Generate (or reuse a cached) combined .d.ts for the kit's public API. */
export function kitApiDts(): string {
    const cacheDir = join(REPO_ROOT, "node_modules", ".vite-cache", "artifact-kit-dts");
    const stampPath = join(cacheDir, "stamp.txt");
    const outPath = join(cacheDir, "kit-api.d.ts");
    const stamp = kitStamp();

    if (existsSync(outPath) && existsSync(stampPath) && readFileSync(stampPath, "utf8") === stamp) {
        return readFileSync(outPath, "utf8");
    }

    mkdirSync(cacheDir, { recursive: true });
    const emitDir = join(cacheDir, "emit");
    const tsconfigPath = join(cacheDir, "tsconfig.json");
    writeFileSync(
        tsconfigPath,
        SafeJSON.stringify(
            {
                compilerOptions: {
                    target: "ESNext",
                    module: "ESNext",
                    moduleResolution: "bundler",
                    jsx: "react-jsx",
                    strict: true,
                    skipLibCheck: true,
                    declaration: true,
                    emitDeclarationOnly: true,
                    rootDir: KIT_DIR,
                    outDir: emitDir,
                    types: [],
                },
                include: [join(KIT_DIR, "**/*")],
            },
            { strict: true },
            4
        )
    );

    const tsgo = join(REPO_ROOT, "node_modules", ".bin", "tsgo");
    const proc = Bun.spawnSync([tsgo, "-p", tsconfigPath], { cwd: cacheDir, stdout: "pipe", stderr: "pipe" });

    if (proc.exitCode !== 0) {
        const detail = `${proc.stdout.toString()}\n${proc.stderr.toString()}`.trim();
        throw new Error(`kit declaration emit failed (tsgo exit ${proc.exitCode}):\n${detail}`);
    }

    const parts: string[] = [
        '// @artifact/kit — generated API reference. Import everything below from "@artifact/kit".',
        "// (index re-exports the modules; the per-module headers are just provenance.)",
    ];

    for (const file of KIT_FILES) {
        if (file === "index.ts") {
            continue;
        }

        const dts = join(emitDir, file.replace(/\.tsx?$/, ".d.ts"));
        parts.push(`\n// ─── ${file} ───\n${readFileSync(dts, "utf8").trim()}`);
    }

    const combined = `${parts.join("\n")}\n`;
    writeFileSync(outPath, combined);
    writeFileSync(stampPath, stamp);
    logger.debug({ outPath }, "[artifact] kit d.ts regenerated");

    return combined;
}

export interface EditorTsconfigResult {
    path: string;
    created: boolean;
}

/** Write an OPTIONAL tsconfig.json into an artifact dir for editor IntelliSense. */
export function writeEditorTsconfig(dir: string): EditorTsconfigResult {
    const path = resolve(dir, "tsconfig.json");

    if (existsSync(path)) {
        return { path, created: false };
    }

    const gt = REPO_ROOT;
    const config = {
        // Generated by `tools artifact types` — editor IntelliSense only; the
        // runtime (tools artifact serve/build) does not need this file.
        compilerOptions: {
            target: "ESNext",
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "react-jsx",
            strict: true,
            noEmit: true,
            skipLibCheck: true,
            paths: {
                "@artifact/kit": [join(gt, "src/artifact/runtime/kit/index.ts")],
                "@genesistools/*": [join(gt, "*")],
                "@genesiscz/utils/*": [join(gt, "src/utils/*")],
                react: [join(gt, "node_modules/@types/react/index.d.ts")],
                "react/jsx-runtime": [join(gt, "node_modules/@types/react/jsx-runtime.d.ts")],
                "react-dom/client": [join(gt, "node_modules/@types/react-dom/client.d.ts")],
            },
        },
    };
    writeFileSync(path, `${SafeJSON.stringify(config, { strict: true }, 4)}\n`);

    return { path, created: true };
}
