/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkitemTypeColorsRouteImport } from './routes/api/workitem-type-colors'
import { Route as ApiUpdateAuthRouteImport } from './routes/api/update-auth'
import { Route as ApiTimelogEntriesRouteImport } from './routes/api/timelog-entries'
import { Route as ApiTestConnectionRouteImport } from './routes/api/test-connection'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiMoveMappingRouteImport } from './routes/api/move-mapping'
import { Route as ApiMappingsRouteImport } from './routes/api/mappings'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiClarityWeeksRouteImport } from './routes/api/clarity-weeks'
import { Route as ApiClarityTasksRouteImport } from './routes/api/clarity-tasks'
import { Route as ApiAdoWorkitemsRouteImport } from './routes/api/ado-workitems'
import { Route as ApiAdoConfigRouteImport } from './routes/api/ado-config'
import { Route as ApiFillPreviewRouteImport } from './routes/api/fill.preview'
import { Route as ApiFillExecuteRouteImport } from './routes/api/fill.execute'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkitemTypeColorsRoute = ApiWorkitemTypeColorsRouteImport.update({
  id: '/api/workitem-type-colors',
  path: '/api/workitem-type-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateAuthRoute = ApiUpdateAuthRouteImport.update({
  id: '/api/update-auth',
  path: '/api/update-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimelogEntriesRoute = ApiTimelogEntriesRouteImport.update({
  id: '/api/timelog-entries',
  path: '/api/timelog-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestConnectionRoute = ApiTestConnectionRouteImport.update({
  id: '/api/test-connection',
  path: '/api/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoveMappingRoute = ApiMoveMappingRouteImport.update({
  id: '/api/move-mapping',
  path: '/api/move-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMappingsRoute = ApiMappingsRouteImport.update({
  id: '/api/mappings',
  path: '/api/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClarityWeeksRoute = ApiClarityWeeksRouteImport.update({
  id: '/api/clarity-weeks',
  path: '/api/clarity-weeks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClarityTasksRoute = ApiClarityTasksRouteImport.update({
  id: '/api/clarity-tasks',
  path: '/api/clarity-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdoWorkitemsRoute = ApiAdoWorkitemsRouteImport.update({
  id: '/api/ado-workitems',
  path: '/api/ado-workitems',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdoConfigRoute = ApiAdoConfigRouteImport.update({
  id: '/api/ado-config',
  path: '/api/ado-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFillPreviewRoute = ApiFillPreviewRouteImport.update({
  id: '/api/fill/preview',
  path: '/api/fill/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFillExecuteRoute = ApiFillExecuteRouteImport.update({
  id: '/api/fill/execute',
  path: '/api/fill/execute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/mappings': typeof MappingsRoute
  '/settings': typeof SettingsRoute
  '/api/ado-config': typeof ApiAdoConfigRoute
  '/api/ado-workitems': typeof ApiAdoWorkitemsRoute
  '/api/clarity-tasks': typeof ApiClarityTasksRoute
  '/api/clarity-weeks': typeof ApiClarityWeeksRoute
  '/api/export': typeof ApiExportRoute
  '/api/mappings': typeof ApiMappingsRoute
  '/api/move-mapping': typeof ApiMoveMappingRoute
  '/api/status': typeof ApiStatusRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/api/timelog-entries': typeof ApiTimelogEntriesRoute
  '/api/update-auth': typeof ApiUpdateAuthRoute
  '/api/workitem-type-colors': typeof ApiWorkitemTypeColorsRoute
  '/api/fill/execute': typeof ApiFillExecuteRoute
  '/api/fill/preview': typeof ApiFillPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/mappings': typeof MappingsRoute
  '/settings': typeof SettingsRoute
  '/api/ado-config': typeof ApiAdoConfigRoute
  '/api/ado-workitems': typeof ApiAdoWorkitemsRoute
  '/api/clarity-tasks': typeof ApiClarityTasksRoute
  '/api/clarity-weeks': typeof ApiClarityWeeksRoute
  '/api/export': typeof ApiExportRoute
  '/api/mappings': typeof ApiMappingsRoute
  '/api/move-mapping': typeof ApiMoveMappingRoute
  '/api/status': typeof ApiStatusRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/api/timelog-entries': typeof ApiTimelogEntriesRoute
  '/api/update-auth': typeof ApiUpdateAuthRoute
  '/api/workitem-type-colors': typeof ApiWorkitemTypeColorsRoute
  '/api/fill/execute': typeof ApiFillExecuteRoute
  '/api/fill/preview': typeof ApiFillPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/mappings': typeof MappingsRoute
  '/settings': typeof SettingsRoute
  '/api/ado-config': typeof ApiAdoConfigRoute
  '/api/ado-workitems': typeof ApiAdoWorkitemsRoute
  '/api/clarity-tasks': typeof ApiClarityTasksRoute
  '/api/clarity-weeks': typeof ApiClarityWeeksRoute
  '/api/export': typeof ApiExportRoute
  '/api/mappings': typeof ApiMappingsRoute
  '/api/move-mapping': typeof ApiMoveMappingRoute
  '/api/status': typeof ApiStatusRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/api/timelog-entries': typeof ApiTimelogEntriesRoute
  '/api/update-auth': typeof ApiUpdateAuthRoute
  '/api/workitem-type-colors': typeof ApiWorkitemTypeColorsRoute
  '/api/fill/execute': typeof ApiFillExecuteRoute
  '/api/fill/preview': typeof ApiFillPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/import'
    | '/mappings'
    | '/settings'
    | '/api/ado-config'
    | '/api/ado-workitems'
    | '/api/clarity-tasks'
    | '/api/clarity-weeks'
    | '/api/export'
    | '/api/mappings'
    | '/api/move-mapping'
    | '/api/status'
    | '/api/test-connection'
    | '/api/timelog-entries'
    | '/api/update-auth'
    | '/api/workitem-type-colors'
    | '/api/fill/execute'
    | '/api/fill/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/import'
    | '/mappings'
    | '/settings'
    | '/api/ado-config'
    | '/api/ado-workitems'
    | '/api/clarity-tasks'
    | '/api/clarity-weeks'
    | '/api/export'
    | '/api/mappings'
    | '/api/move-mapping'
    | '/api/status'
    | '/api/test-connection'
    | '/api/timelog-entries'
    | '/api/update-auth'
    | '/api/workitem-type-colors'
    | '/api/fill/execute'
    | '/api/fill/preview'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/import'
    | '/mappings'
    | '/settings'
    | '/api/ado-config'
    | '/api/ado-workitems'
    | '/api/clarity-tasks'
    | '/api/clarity-weeks'
    | '/api/export'
    | '/api/mappings'
    | '/api/move-mapping'
    | '/api/status'
    | '/api/test-connection'
    | '/api/timelog-entries'
    | '/api/update-auth'
    | '/api/workitem-type-colors'
    | '/api/fill/execute'
    | '/api/fill/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  ImportRoute: typeof ImportRoute
  MappingsRoute: typeof MappingsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAdoConfigRoute: typeof ApiAdoConfigRoute
  ApiAdoWorkitemsRoute: typeof ApiAdoWorkitemsRoute
  ApiClarityTasksRoute: typeof ApiClarityTasksRoute
  ApiClarityWeeksRoute: typeof ApiClarityWeeksRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiMappingsRoute: typeof ApiMappingsRoute
  ApiMoveMappingRoute: typeof ApiMoveMappingRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiTestConnectionRoute: typeof ApiTestConnectionRoute
  ApiTimelogEntriesRoute: typeof ApiTimelogEntriesRoute
  ApiUpdateAuthRoute: typeof ApiUpdateAuthRoute
  ApiWorkitemTypeColorsRoute: typeof ApiWorkitemTypeColorsRoute
  ApiFillExecuteRoute: typeof ApiFillExecuteRoute
  ApiFillPreviewRoute: typeof ApiFillPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workitem-type-colors': {
      id: '/api/workitem-type-colors'
      path: '/api/workitem-type-colors'
      fullPath: '/api/workitem-type-colors'
      preLoaderRoute: typeof ApiWorkitemTypeColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-auth': {
      id: '/api/update-auth'
      path: '/api/update-auth'
      fullPath: '/api/update-auth'
      preLoaderRoute: typeof ApiUpdateAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timelog-entries': {
      id: '/api/timelog-entries'
      path: '/api/timelog-entries'
      fullPath: '/api/timelog-entries'
      preLoaderRoute: typeof ApiTimelogEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-connection': {
      id: '/api/test-connection'
      path: '/api/test-connection'
      fullPath: '/api/test-connection'
      preLoaderRoute: typeof ApiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/move-mapping': {
      id: '/api/move-mapping'
      path: '/api/move-mapping'
      fullPath: '/api/move-mapping'
      preLoaderRoute: typeof ApiMoveMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mappings': {
      id: '/api/mappings'
      path: '/api/mappings'
      fullPath: '/api/mappings'
      preLoaderRoute: typeof ApiMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clarity-weeks': {
      id: '/api/clarity-weeks'
      path: '/api/clarity-weeks'
      fullPath: '/api/clarity-weeks'
      preLoaderRoute: typeof ApiClarityWeeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clarity-tasks': {
      id: '/api/clarity-tasks'
      path: '/api/clarity-tasks'
      fullPath: '/api/clarity-tasks'
      preLoaderRoute: typeof ApiClarityTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ado-workitems': {
      id: '/api/ado-workitems'
      path: '/api/ado-workitems'
      fullPath: '/api/ado-workitems'
      preLoaderRoute: typeof ApiAdoWorkitemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ado-config': {
      id: '/api/ado-config'
      path: '/api/ado-config'
      fullPath: '/api/ado-config'
      preLoaderRoute: typeof ApiAdoConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fill/preview': {
      id: '/api/fill/preview'
      path: '/api/fill/preview'
      fullPath: '/api/fill/preview'
      preLoaderRoute: typeof ApiFillPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fill/execute': {
      id: '/api/fill/execute'
      path: '/api/fill/execute'
      fullPath: '/api/fill/execute'
      preLoaderRoute: typeof ApiFillExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  ImportRoute: ImportRoute,
  MappingsRoute: MappingsRoute,
  SettingsRoute: SettingsRoute,
  ApiAdoConfigRoute: ApiAdoConfigRoute,
  ApiAdoWorkitemsRoute: ApiAdoWorkitemsRoute,
  ApiClarityTasksRoute: ApiClarityTasksRoute,
  ApiClarityWeeksRoute: ApiClarityWeeksRoute,
  ApiExportRoute: ApiExportRoute,
  ApiMappingsRoute: ApiMappingsRoute,
  ApiMoveMappingRoute: ApiMoveMappingRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiTestConnectionRoute: ApiTestConnectionRoute,
  ApiTimelogEntriesRoute: ApiTimelogEntriesRoute,
  ApiUpdateAuthRoute: ApiUpdateAuthRoute,
  ApiWorkitemTypeColorsRoute: ApiWorkitemTypeColorsRoute,
  ApiFillExecuteRoute: ApiFillExecuteRoute,
  ApiFillPreviewRoute: ApiFillPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
