import type { PairingPayload } from "@dd/contract";
import * as SecureStore from "expo-secure-store";
import Storage from "expo-sqlite/kv-store";
import type {
    SavedConnection,
    SavedConnectionInput,
    SavedConnectionPatch,
} from "@/features/connections/types";
import type { DiscoveredAgent } from "@/transport/lan-discovery";
import { createCloudflaredTransport } from "@/transport/tiers/cloudflared";
import { createLanTransport, type LanCredentials } from "@/transport/tiers/lan";
import { createManagedTransport } from "@/transport/tiers/managed";
import { createTailscaleTransport } from "@/transport/tiers/tailscale";
import type { Transport, TransportTier } from "@/transport/Transport";

const CONNECTIONS_KEY = "dd.connections";
const ACTIVE_ID_KEY = "dd.activeConnectionId";
const PASSWORD_ITEM_PREFIX = "dd_basic_password_";

/**
 * SecureStore keychain accounts must match `[A-Za-z0-9._-]`. Connection ids are generated by
 * `makeId()` so they already satisfy this, but the prefix join is kept explicit + centralized so the
 * read/write/delete sides can never drift.
 */
function passwordItemKey(id: string): string {
    return `${PASSWORD_ITEM_PREFIX}${id}`;
}

function makeId(): string {
    return `conn_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

async function readPassword(id: string): Promise<string> {
    try {
        const value = await SecureStore.getItemAsync(passwordItemKey(id));
        return value ?? "";
    } catch (err) {
        console.warn(`[connections] failed to read password for ${id}`, err);
        return "";
    }
}

async function writePassword(id: string, password: string): Promise<void> {
    await SecureStore.setItemAsync(passwordItemKey(id), password, {
        keychainAccessible: SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY,
    });
}

async function deletePassword(id: string): Promise<void> {
    try {
        await SecureStore.deleteItemAsync(passwordItemKey(id));
    } catch (err) {
        console.warn(`[connections] failed to delete password for ${id}`, err);
    }
}

function isSavedConnection(value: unknown): value is SavedConnection {
    if (typeof value !== "object" || value === null) {
        return false;
    }

    const v = value as Record<string, unknown>;
    return (
        typeof v.id === "string" &&
        typeof v.label === "string" &&
        typeof v.tier === "string" &&
        typeof v.baseUrl === "string" &&
        typeof v.host === "string" &&
        typeof v.port === "number" &&
        typeof v.username === "string" &&
        typeof v.addedAt === "number" &&
        typeof v.lastUsedAt === "number"
    );
}

/** Reads + validates the persisted connection list; tolerates corrupt/legacy payloads by ignoring them. */
export async function loadConnections(): Promise<SavedConnection[]> {
    try {
        const raw = await Storage.getItem(CONNECTIONS_KEY);

        if (!raw) {
            return [];
        }

        const parsed: unknown = JSON.parse(raw);

        if (!Array.isArray(parsed)) {
            console.warn("[connections] stored connections were not an array; ignoring");
            return [];
        }

        return parsed.filter(isSavedConnection);
    } catch (err) {
        console.warn("[connections] failed to load saved connections", err);
        return [];
    }
}

async function persistConnections(list: SavedConnection[]): Promise<void> {
    await Storage.setItem(CONNECTIONS_KEY, JSON.stringify(list));
}

export async function getActiveConnectionId(): Promise<string | null> {
    try {
        return await Storage.getItem(ACTIVE_ID_KEY);
    } catch (err) {
        console.warn("[connections] failed to read active connection id", err);
        return null;
    }
}

async function setActiveConnectionId(id: string | null): Promise<void> {
    if (id === null) {
        await Storage.removeItem(ACTIVE_ID_KEY);
        return;
    }

    await Storage.setItem(ACTIVE_ID_KEY, id);
}

/**
 * Rebuilds the live transport for a saved connection, re-reading its password from SecureStore. This
 * is the single place that maps a persisted (password-less) row back into a working `Transport`, so
 * both `activate` and boot-time `restore` go through it.
 */
export async function buildTransportFor(conn: SavedConnection): Promise<Transport> {
    const password = await readPassword(conn.id);

    if (conn.tier === "tailscale") {
        return createTailscaleTransport({
            tailnetHost: conn.host,
            port: conn.port,
            username: conn.username,
            password,
        });
    }

    if (conn.tier === "cloudflared-self") {
        const pairing: PairingPayload = {
            baseUrl: conn.baseUrl,
            tier: "cloudflared-self",
            username: conn.username,
        };
        return createCloudflaredTransport(pairing, password);
    }

    if (conn.tier === "managed") {
        const pairing: PairingPayload = { baseUrl: conn.baseUrl, tier: "managed", username: conn.username };
        return createManagedTransport(pairing);
    }

    const agent: DiscoveredAgent = {
        name: conn.label || conn.host,
        host: conn.host,
        port: conn.port,
        baseUrl: conn.baseUrl,
    };
    const creds: LanCredentials = { username: conn.username, password };
    return createLanTransport(agent, creds);
}

function defaultLabel({ host, port, tier }: { host: string; port: number; tier: TransportTier }): string {
    if (tier === "lan") {
        return `${host}:${port}`;
    }

    return `${host} (${tier})`;
}

/**
 * Upserts a connection by `(tier, baseUrl)` identity so re-connecting the same agent through the
 * Connect flow updates the existing row instead of stacking duplicates. Persists the password to
 * SecureStore, marks the row active + freshens `lastUsedAt`, and returns the resolved id.
 */
export async function upsertConnection(input: SavedConnectionInput): Promise<string> {
    const list = await loadConnections();
    const now = Date.now();
    const existing = list.find((c) => c.tier === input.tier && c.baseUrl === input.baseUrl);
    const id = existing ? existing.id : makeId();

    if (input.password !== undefined) {
        await writePassword(id, input.password);
    }

    const label = input.label?.trim() || existing?.label || defaultLabel({ host: input.host, port: input.port, tier: input.tier });
    const next: SavedConnection = {
        id,
        label,
        tier: input.tier,
        baseUrl: input.baseUrl,
        host: input.host,
        port: input.port,
        username: input.username,
        addedAt: existing?.addedAt ?? now,
        lastUsedAt: now,
    };
    const merged = existing
        ? list.map((c) => (c.id === id ? next : c))
        : [...list, next];

    await persistConnections(merged);
    await setActiveConnectionId(id);
    return id;
}

export async function updateConnection(id: string, patch: SavedConnectionPatch): Promise<SavedConnection | null> {
    const list = await loadConnections();
    const target = list.find((c) => c.id === id);

    if (!target) {
        console.warn(`[connections] updateConnection: no connection ${id}`);
        return null;
    }

    if (patch.password !== undefined) {
        await writePassword(id, patch.password);
    }

    const host = patch.host ?? target.host;
    const port = patch.port ?? target.port;
    const baseUrl = patch.baseUrl ?? (patch.host || patch.port ? `http://${host}:${port}` : target.baseUrl);
    const updated: SavedConnection = {
        ...target,
        label: patch.label?.trim() || target.label,
        host,
        port,
        username: patch.username ?? target.username,
        baseUrl,
    };

    await persistConnections(list.map((c) => (c.id === id ? updated : c)));
    return updated;
}

/** Removes a connection + its SecureStore password; clears the active id if it pointed at this row. */
export async function deleteConnection(id: string): Promise<void> {
    const list = await loadConnections();
    await persistConnections(list.filter((c) => c.id !== id));
    await deletePassword(id);

    const activeId = await getActiveConnectionId();

    if (activeId === id) {
        await setActiveConnectionId(null);
    }
}

/** Stamps `lastUsedAt` + marks the row active (called when a connection is activated). */
export async function markActivated(id: string): Promise<SavedConnection | null> {
    const list = await loadConnections();
    const target = list.find((c) => c.id === id);

    if (!target) {
        console.warn(`[connections] markActivated: no connection ${id}`);
        return null;
    }

    const updated: SavedConnection = { ...target, lastUsedAt: Date.now() };
    await persistConnections(list.map((c) => (c.id === id ? updated : c)));
    await setActiveConnectionId(id);
    return updated;
}

export async function getConnection(id: string): Promise<SavedConnection | null> {
    const list = await loadConnections();
    return list.find((c) => c.id === id) ?? null;
}
