import { describe, expect, test } from "bun:test";
import { cleanPromptText, subdirOf } from "@app/claude/lib/cmux/sessions";

describe("cleanPromptText", () => {
    test("keeps ordinary prompt text unchanged", () => {
        expect(cleanPromptText("fix the auth callback")).toBe("fix the auth callback");
    });

    /** Verbatim from session 8b6e69bf, which produced the tab `<local-command-caveat>Caveat: T…`. */
    test("drops the caveat block a slash-command session starts with", () => {
        const raw =
            "<local-command-caveat>Caveat: The messages below were generated by the user while running local " +
            "commands. DO NOT respond to these messages.</local-command-caveat>\n" +
            "<command-name>/model</command-name>\n" +
            "give me the cmux restore tool";

        expect(cleanPromptText(raw)).toBe("give me the cmux restore tool");
    });

    /** Verbatim shape from session 3c96c6d9: a status line pasted above the real question. */
    test("drops a pasted status line and keeps the question", () => {
        const raw =
            " claude-opus-5 GenesisTools feat/claude-cmux-restore\n" +
            "  313k/775k(40%) +1.6k AC 8b6e69bf @10:17:44 ⚿ personal\n" +
            "  ⏵⏵ bypass permissions on (shift+tab to cycle) · ← for agents\n\n" +
            "it still shows the old data";

        expect(cleanPromptText(raw)).toBe("it still shows the old data");
    });

    test("a prompt that is only noise yields null, so the caller falls back", () => {
        expect(cleanPromptText("<system-reminder>background context</system-reminder>")).toBeNull();
        expect(cleanPromptText("   ")).toBeNull();
        expect(cleanPromptText(null)).toBeNull();
    });

    test("caps the length, since this text also becomes a cmux tab name", () => {
        const long = cleanPromptText("word ".repeat(200));

        expect(long?.length).toBeLessThanOrEqual(120);
        expect(long?.endsWith("…")).toBe(true);
    });
});

describe("subdirOf", () => {
    test("the project root itself adds nothing", () => {
        expect(subdirOf("/Users/me/Projects/GenesisTools", "GenesisTools")).toBeNull();
    });

    test("a nested worktree shows the tail below the root", () => {
        expect(subdirOf("/Users/me/Projects/GenesisTools/.worktrees/fix", "GenesisTools")).toBe(".worktrees/fix");
    });

    /**
     * Claude Code files a SIBLING worktree (`web-app-issue-4821`, next to `web-app`) under
     * the plain project. Without this branch several different worktrees all render as
     * `web-app` and the picker cannot tell them apart.
     */
    test("a sibling worktree shows what distinguishes it, minus the repeated project name", () => {
        expect(subdirOf("/Users/me/Projects/acme/web-app-issue-4821-burn-auth", "web-app")).toBe(
            "issue-4821-burn-auth"
        );
    });

    test("an unrelated directory shows its own name", () => {
        expect(subdirOf("/Users/me/scratch/experiment", "web-app")).toBe("experiment");
    });

    test("a package inside the repo keeps its full path tail", () => {
        expect(subdirOf("/Users/me/Projects/app/packages/web", "app")).toBe("packages/web");
    });
});
