import { chmodSync, existsSync, readFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { env } from "@genesiscz/utils/env";
import { SafeJSON } from "@genesiscz/utils/json";
import { logger } from "@genesiscz/utils/logger";
import { browserExtensionStorage } from "../config";
import { NATIVE_HOST_NAME } from "./messages";

const log = logger.child({ component: "browser-extension/install" });

export const EXTENSION_SOURCE_DIR = resolve(import.meta.dirname, "..", "..", "extension");
export const HOST_ENTRY = resolve(import.meta.dirname, "..", "..", "host", "main.ts");

/**
 * The id Chromium gives an extension whose manifest carries `key`: sha256 of the DER public key,
 * first 32 hex digits, each digit 0-f written as a letter a-p.
 */
export function extensionIdFromKey(base64Key: string): string {
    const der = Buffer.from(base64Key, "base64");
    const hex = new Bun.CryptoHasher("sha256").update(der).digest("hex").slice(0, 32);
    return [...hex].map((digit) => String.fromCharCode(97 + Number.parseInt(digit, 16))).join("");
}

/** The pinned id, read from the source manifest's `key`. */
export function pinnedExtensionId(manifestPath = join(EXTENSION_SOURCE_DIR, "manifest.json")): string {
    const manifest: unknown = SafeJSON.parse(readFileSync(manifestPath, "utf8"), { strict: true });
    const key = typeof manifest === "object" && manifest !== null && "key" in manifest ? manifest.key : undefined;

    if (typeof key !== "string" || key.length < 100) {
        throw new Error(`${manifestPath} has no public "key"; the extension id would change per folder`);
    }

    return extensionIdFromKey(key);
}

export interface BrowserHostDir {
    browser: string;
    /** The browser's user-data folder; the host is registered only for browsers that have one. */
    profileDir: string;
    hostDir: string;
}

export function browserHostDirs(home = homedir()): BrowserHostDir[] {
    const support = join(home, "Library", "Application Support");
    const browsers: [string, string][] = [
        ["Brave", join(support, "BraveSoftware", "Brave-Browser")],
        ["Chrome", join(support, "Google", "Chrome")],
        ["Chromium", join(support, "Chromium")],
    ];

    return browsers.map(([browser, profileDir]) => ({
        browser,
        profileDir,
        hostDir: join(profileDir, "NativeMessagingHosts"),
    }));
}

export function launcherPath(): string {
    return join(browserExtensionStorage().getBaseDir(), "native-host.ts");
}

/**
 * The executable the browser starts. Browsers launch hosts with a bare PATH, so it pins the bun
 * binary in its shebang and the PATH of the shell that installed it (for git, claude, cursor, cmux).
 * It is a TypeScript file run by bun, not a shell script.
 */
export function launcherSource({
    bunPath,
    pathEnv,
    hostEntry,
}: {
    bunPath: string;
    pathEnv: string;
    hostEntry: string;
}): string {
    return [
        `#!${bunPath}`,
        "// Generated by `tools browser-extension install-host`. Run that again instead of editing this file.",
        `process.env.PATH = ${SafeJSON.stringify(pathEnv, { strict: true })};`,
        `await import(${SafeJSON.stringify(hostEntry, { strict: true })});`,
        "",
    ].join("\n");
}

export function hostManifest({ launcher, extensionId }: { launcher: string; extensionId: string }) {
    return {
        name: NATIVE_HOST_NAME,
        description: "GenesisTools browser extension host",
        path: launcher,
        type: "stdio",
        allowed_origins: [`chrome-extension://${extensionId}/`],
    };
}

export interface InstallResult {
    extensionId: string;
    launcher: string;
    registered: { browser: string; manifest: string }[];
    skipped: string[];
}

export async function installHost(): Promise<InstallResult> {
    const extensionId = pinnedExtensionId();
    const launcher = launcherPath();
    await mkdir(dirname(launcher), { recursive: true });
    await Bun.write(
        launcher,
        launcherSource({
            bunPath: Bun.which("bun") ?? process.execPath,
            pathEnv: env.getProcessEnv().PATH ?? "",
            hostEntry: HOST_ENTRY,
        })
    );
    chmodSync(launcher, 0o755);
    const manifest = SafeJSON.stringify(hostManifest({ launcher, extensionId }), null, 2);
    const result: InstallResult = { extensionId, launcher, registered: [], skipped: [] };

    for (const dir of browserHostDirs()) {
        if (!existsSync(dir.profileDir)) {
            result.skipped.push(dir.browser);
            continue;
        }

        await mkdir(dir.hostDir, { recursive: true });
        const path = join(dir.hostDir, `${NATIVE_HOST_NAME}.json`);
        await Bun.write(path, `${manifest}\n`);
        result.registered.push({ browser: dir.browser, manifest: path });
    }

    log.info({ extensionId, launcher, registered: result.registered.map((r) => r.browser) }, "native host installed");
    return result;
}

export interface HostStatus {
    extensionId: string;
    launcher: string;
    launcherExists: boolean;
    browsers: { browser: string; manifest: string; registered: boolean; allowsThisId: boolean }[];
}

export function hostStatus(): HostStatus {
    const extensionId = pinnedExtensionId();
    const launcher = launcherPath();

    return {
        extensionId,
        launcher,
        launcherExists: existsSync(launcher),
        browsers: browserHostDirs()
            .filter((dir) => existsSync(dir.profileDir))
            .map((dir) => {
                const manifest = join(dir.hostDir, `${NATIVE_HOST_NAME}.json`);
                const registered = existsSync(manifest);
                return {
                    browser: dir.browser,
                    manifest,
                    registered,
                    allowsThisId:
                        registered && readFileSync(manifest, "utf8").includes(`chrome-extension://${extensionId}/`),
                };
            }),
    };
}
