/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FirstRunRouteImport } from './routes/first-run'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as ChannelsHandleRouteImport } from './routes/channels.$handle'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstRunRoute = FirstRunRouteImport.update({
  id: '/first-run',
  path: '/first-run',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const ChannelsHandleRoute = ChannelsHandleRouteImport.update({
  id: '/channels/$handle',
  path: '/channels/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/first-run': typeof FirstRunRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/channels/$handle': typeof ChannelsHandleRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/first-run': typeof FirstRunRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/channels/$handle': typeof ChannelsHandleRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/first-run': typeof FirstRunRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/channels/$handle': typeof ChannelsHandleRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/first-run'
    | '/history'
    | '/jobs'
    | '/settings'
    | '/channels/$handle'
    | '/collections/$id'
    | '/videos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/first-run'
    | '/history'
    | '/jobs'
    | '/settings'
    | '/channels/$handle'
    | '/collections/$id'
    | '/videos/$id'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/first-run'
    | '/history'
    | '/jobs'
    | '/settings'
    | '/channels/$handle'
    | '/collections/$id'
    | '/videos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  FirstRunRoute: typeof FirstRunRoute
  HistoryRoute: typeof HistoryRoute
  JobsRoute: typeof JobsRoute
  SettingsRoute: typeof SettingsRoute
  ChannelsHandleRoute: typeof ChannelsHandleRoute
  VideosIdRoute: typeof VideosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-run': {
      id: '/first-run'
      path: '/first-run'
      fullPath: '/first-run'
      preLoaderRoute: typeof FirstRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/channels/$handle': {
      id: '/channels/$handle'
      path: '/channels/$handle'
      fullPath: '/channels/$handle'
      preLoaderRoute: typeof ChannelsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  FirstRunRoute: FirstRunRoute,
  HistoryRoute: HistoryRoute,
  JobsRoute: JobsRoute,
  SettingsRoute: SettingsRoute,
  ChannelsHandleRoute: ChannelsHandleRoute,
  VideosIdRoute: VideosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
