import { SafeJSON } from "@app/utils/json";
import pc from "picocolors";
import type { FileReport, ScanReport } from "./types";

export function renderJson(report: ScanReport): string {
    return SafeJSON.stringify(report, null, 2);
}

function survivalSummary(file: FileReport): string {
    const { churnCount, inboundImports, hasCoverage } = file.survival;
    return `churn ${churnCount} · imports ${inboundImports} · coverage ${hasCoverage ? "yes" : "no"}`;
}

export function renderHuman(report: ScanReport): string {
    const lines: string[] = [];
    const dying = report.files.filter((f) => f.status === "dying");
    const dead = report.files.filter((f) => f.status === "dead");
    const rescued = report.files.filter((f) => f.status === "rescued");

    lines.push(pc.bold(`apoptosis — ${report.dir} (${report.churnDays}d churn window, ${report.graceDays}d grace)`));
    lines.push(
        `scanned ${report.counts.scanned} files · ${report.counts.candidates} candidates · ` +
            `${report.counts.rescued} rescued this run · ${report.counts.ready} ready to die`
    );

    if (dying.length > 0) {
        lines.push("");
        lines.push(pc.yellow("DYING (marked, grace not elapsed)"));
        for (const f of dying) {
            lines.push(`  ${f.path}  ${survivalSummary(f)}  marked ${f.daysMarked}d ago (${f.daysLeft}d left)`);
        }
    }

    if (dead.length > 0) {
        lines.push("");
        lines.push(pc.red("READY TO DIE (grace elapsed — apoptosis complete)"));
        for (const f of dead) {
            lines.push(`  ${f.path}  ${survivalSummary(f)}  marked ${f.daysMarked}d ago (committed apoptosis)`);
        }
    }

    if (rescued.length > 0) {
        lines.push("");
        lines.push(pc.green("RESCUED (regained a survival signal since last run)"));
        for (const f of rescued) {
            lines.push(`  ${f.path}  ${survivalSummary(f)}  mark cleared`);
        }
    }

    return lines.join("\n");
}

/** Single-quote a path for safe use in a POSIX shell command, escaping embedded quotes. */
function shQuote(path: string): string {
    return `'${path.replace(/'/g, "'\\''")}'`;
}

export function renderKillScript(report: ScanReport): string {
    const dead = report.files.filter((f) => f.status === "dead");
    const lines = [
        "#!/usr/bin/env bash",
        "# Generated by `tools apoptosis kill`. REVIEW before running — this deletes files.",
        "# These files had zero survival signals continuously through the grace window.",
        "set -euo pipefail",
        "",
    ];
    for (const f of dead) {
        const quoted = shQuote(f.path);
        lines.push(`git rm -- ${quoted} 2>/dev/null || rm -f -- ${quoted}`);
    }

    return lines.join("\n");
}

export function renderPrBody(report: ScanReport): string {
    const dead = report.files.filter((f) => f.status === "dead");
    const lines = [
        "## Dead code removal (apoptosis)",
        "",
        "The following files had **zero survival signals** (no recent churn, no inbound imports, no coverage) continuously through the grace window:",
        "",
    ];
    for (const f of dead) {
        lines.push(`- [ ] \`${f.path}\``);
    }

    return lines.join("\n");
}
