import {
    accessSync,
    chmodSync,
    constants,
    existsSync,
    mkdirSync,
    readdirSync,
    realpathSync,
    statSync,
    unlinkSync,
    writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { env } from "@genesiscz/utils/env";
import { logger } from "@genesiscz/utils/logger";
import { shellSingleQuote } from "./shell-quote";

/**
 * Claude Code's tmux teammate spawn only forwards a hard-coded env allowlist
 * (`LW_` in the bundle). `CLAUDE_CODE_OAUTH_TOKEN` is intentionally absent
 * (it lives in the secrets list `X_e`), so agent-team panes launched under
 * `tools cc run <account>` come up as "Not logged in".
 *
 * Escape hatch (still present in CC): `CLAUDE_CODE_TEAMMATE_COMMAND` replaces
 * the binary path used for teammate processes. We point it at a per-launch
 * mode-700 wrapper that hardcodes the lead's OAuth launch env, then execs the
 * real claude binary with the original `--agent-id …` args.
 *
 * Per-PID wrappers keep concurrent multi-account leads isolated (no shared
 * `active.env` race). See Claude/Bugs/TeammateTmuxNotRespectingOauthTokens.md.
 */

export interface TeammateAuthEnv {
    oauthToken: string;
    subscriptionType: string;
    accountName: string;
    fableModel?: string;
    customModelOption?: string;
    customModelOptionName?: string;
    customModelOptionDescription?: string;
}

export interface InstallTeammateWrapperInput {
    env: TeammateAuthEnv;
    /** Absolute path to the real `claude` binary. */
    claudeBin: string;
    /** Override dir (tests). Default: ~/.genesis-tools/claude/teammate-wrappers */
    dir?: string;
    /** Override unique id (tests). Default: `${pid}-${random}` */
    id?: string;
}

export interface InstalledTeammateWrapper {
    path: string;
}

export function teammateWrappersDir(): string {
    return join(env.paths.getHome() ?? homedir(), ".genesis-tools", "claude", "teammate-wrappers");
}

/**
 * Resolve a real executable for teammate panes. Must be a file path, not a shell
 * function (`ccc`/`claude` wrappers from rc) — CC execs TEAMMATE_COMMAND directly.
 */
export function resolveClaudeBinaryForTeammates(): string {
    const home = env.paths.getHome() ?? homedir();
    const candidates = [
        join(home, ".bun", "bin", "claude"),
        join(home, ".local", "bin", "claude"),
        Bun.which("claude") ?? undefined,
    ].filter((p): p is string => Boolean(p));

    for (const candidate of candidates) {
        try {
            if (!existsSync(candidate)) {
                continue;
            }

            accessSync(candidate, constants.X_OK);
            return realpathSync(candidate);
        } catch (error) {
            logger.debug({ error, candidate }, "[teammate-wrapper] candidate claude binary not usable; trying next");
        }
    }

    // Last resort: leave it on PATH for the wrapper's exec, because aborting the
    // LEAD launch over a teammate's binary is the worse failure.
    //
    // The one way this still works is a tmux pane whose PATH carries a `claude`
    // this process's PATH does not, which is why it is not a hard error. What it
    // can NEVER be is a shell function or alias, as the previous comment here
    // suggested: the wrapper is `#!/usr/bin/env bash` with `set -euo pipefail`,
    // sources no profile, and ends in `exec`, so only a real executable resolves.
    // Bun.which already looked, so error level rather than warn: this is a
    // probably-broken teammate, and the log is the only place that says so.
    logger.error(
        "[teammate-wrapper] no executable `claude` found (checked ~/.bun/bin, ~/.local/bin and PATH). " +
            "The wrapper will exec `claude` and the teammate will fail unless the tmux pane's PATH has one. " +
            "Install it somewhere on PATH, or point the lead at an absolute path."
    );
    return "claude";
}

export function buildTeammateWrapperScript(input: { claudeBin: string; env: TeammateAuthEnv }): string {
    const { claudeBin, env: auth } = input;
    const exports: Array<[string, string]> = [
        ["TOOLS_CLAUDE_ACCOUNT", auth.accountName],
        ["CLAUDE_CODE_OAUTH_TOKEN", auth.oauthToken],
        ["CLAUDE_CODE_SUBSCRIPTION_TYPE", auth.subscriptionType],
    ];

    if (auth.fableModel) {
        exports.push(["ANTHROPIC_DEFAULT_FABLE_MODEL", auth.fableModel]);
    }

    if (auth.customModelOption) {
        exports.push(["ANTHROPIC_CUSTOM_MODEL_OPTION", auth.customModelOption]);
    }

    if (auth.customModelOptionName) {
        exports.push(["ANTHROPIC_CUSTOM_MODEL_OPTION_NAME", auth.customModelOptionName]);
    }

    if (auth.customModelOptionDescription) {
        exports.push(["ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION", auth.customModelOptionDescription]);
    }

    const exportLines = exports.map(([k, v]) => `export ${k}=${shellSingleQuote(v)}`).join("\n");

    return `#!/usr/bin/env bash
# Generated by tools cc run — do not edit. Deleted when the lead session exits.
# Injects OAuth launch env into Claude Code agent-team tmux teammates
# (CC's spawn allowlist does not forward CLAUDE_CODE_OAUTH_TOKEN).
set -euo pipefail
${exportLines}
exec ${shellSingleQuote(claudeBin)} "$@"
`;
}

/** The wrapper holds the OAuth token in plaintext — owner-only, never group/other. */
const WRAPPER_MODE = 0o700;

export function installTeammateWrapper(input: InstallTeammateWrapperInput): InstalledTeammateWrapper {
    const dir = input.dir ?? teammateWrappersDir();
    mkdirSync(dir, { recursive: true, mode: WRAPPER_MODE });

    // mkdirSync's mode applies only when it CREATES the directory. A dir inherited
    // from an older build (or a looser umask) keeps its own mode, so re-assert it
    // before writing a token inside.
    chmodSync(dir, WRAPPER_MODE);

    const id = input.id ?? `${process.pid}-${Math.random().toString(36).slice(2, 10)}`;
    const path = join(dir, `wrapper-${id}.sh`);
    const script = buildTeammateWrapperScript({
        claudeBin: input.claudeBin,
        env: input.env,
    });

    // "wx" (exclusive create) rather than "w": open(2) ignores the creation mode
    // when the file already exists, so writing into a pre-created wrapper would
    // silently inherit ITS mode and put the OAuth token there. Failing is correct —
    // the caller degrades to teammates without OAuth instead of leaking a token.
    writeFileSync(path, script, { mode: WRAPPER_MODE, flag: "wx" });

    // umask can only clear permission bits, never add them, so the mode above is an
    // upper bound on any POSIX filesystem. Verify anyway and fail closed: a mount
    // that ignores creation modes must not silently hand out a readable token.
    chmodSync(path, WRAPPER_MODE);
    const mode = statSync(path).mode & 0o777;

    if ((mode & 0o077) !== 0) {
        unlinkSync(path);
        throw new Error(`teammate wrapper ${path} landed with mode ${mode.toString(8)}; refusing to store the token`);
    }

    logger.debug(
        { path, account: input.env.accountName, claudeBin: input.claudeBin },
        "[teammate-wrapper] installed CLAUDE_CODE_TEAMMATE_COMMAND wrapper"
    );

    return { path };
}

export function removeTeammateWrapper(path: string | undefined): void {
    if (!path) {
        return;
    }

    try {
        if (existsSync(path)) {
            unlinkSync(path);
            logger.debug({ path }, "[teammate-wrapper] removed");
        }
    } catch (error) {
        logger.warn({ error, path }, "[teammate-wrapper] failed to remove wrapper");
    }
}

/** Drop wrappers older than maxAgeMs (default 7d). Best-effort; never throws. */
export function sweepStaleTeammateWrappers(maxAgeMs = 7 * 24 * 60 * 60 * 1000, dir?: string): number {
    const root = dir ?? teammateWrappersDir();
    if (!existsSync(root)) {
        return 0;
    }

    let removed = 0;
    try {
        const now = Date.now();
        for (const name of readdirSync(root)) {
            if (!name.startsWith("wrapper-") || !name.endsWith(".sh")) {
                continue;
            }

            const full = join(root, name);
            try {
                const st = statSync(full);
                if (now - st.mtimeMs > maxAgeMs) {
                    unlinkSync(full);
                    removed++;
                }
            } catch (error) {
                logger.debug({ error, full }, "[teammate-wrapper] could not sweep wrapper; leaving it in place");
            }
        }
    } catch (error) {
        logger.debug({ error, root }, "[teammate-wrapper] sweep failed");
    }

    return removed;
}
