#!/usr/bin/env bun
/**
 * Build-time generator for Driver B's xterm.js host page. Inlines `@xterm/xterm` (JS + CSS) and
 * `@xterm/addon-fit` from node_modules into a single self-contained HTML string, wraps it in the
 * bridge glue (the `message`/`postMessage` protocol + `window.__ddFit/__ddScroll/__ddScrollPage/
 * __ddFocus` globals that `bridge.ts` injects against), and writes a committed
 * `xterm-host.generated.ts` exporting the HTML constant. The renderer imports that constant for
 * `source={{ html }}` so there's no build prerequisite at bundle time (the artifact is in git).
 *
 * Re-run after bumping @xterm/*:  bun run src/features/terminals/scripts/build-xterm-host.ts
 *
 * xterm/addon-fit are build-time-only (devDeps): they are inlined here and NEVER imported by RN at
 * runtime, so they are not a runtime/native dependency.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const mobileRoot = resolve(here, "../../../..");
const out = join(here, "..", "xterm-host.generated.ts");

function read(rel: string): string {
    return readFileSync(join(mobileRoot, rel), "utf8");
}

const xtermJs = read("node_modules/@xterm/xterm/lib/xterm.js");
const xtermCss = read("node_modules/@xterm/xterm/css/xterm.css");
const fitJs = read("node_modules/@xterm/addon-fit/lib/addon-fit.js");

// The bridge glue. RN→WebView: a synthetic "message" event carries base64 ttyd output → term.write.
// WebView→RN: term.onData → postMessage({t:"data", payload:base64}). Globals match `bridge.ts`.
const glue = `
const _enc = (u8) => { let s = ""; for (let i = 0; i < u8.length; i++) s += String.fromCharCode(u8[i]); return btoa(s); };
const _dec = (b64) => { const bin = atob(b64); const u8 = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i); return u8; };
const _post = (m) => window.ReactNativeWebView && window.ReactNativeWebView.postMessage(JSON.stringify(m));

const term = new Terminal({
  cursorBlink: true,
  fontFamily: "Menlo, Monaco, 'Courier New', monospace",
  fontSize: 13,
  theme: { background: "#0c0e10", foreground: "#e6edf3", cursor: "#34d399" },
  scrollback: 5000,
  convertEol: false,
});
// RENDERER SWAP POINT: swap \`new Terminal(...)\` + addon wiring for ghostty-web here (research 10);
// it needs \`await init()\` and a WASM blob inlined — single-threaded, no SharedArrayBuffer needed.
const fit = new FitAddon.FitAddon();
term.loadAddon(fit);
term.open(document.getElementById("root"));

const _fit = () => { try { fit.fit(); } catch (e) {} };
_fit();

// RN → WebView: incoming ttyd output frames (base64).
window.addEventListener("message", (ev) => {
  try { term.write(_dec(ev.data)); } catch (e) {}
});

// WebView → RN: user keystrokes.
term.onData((data) => {
  const u8 = new TextEncoder().encode(data);
  _post({ t: "data", payload: _enc(u8) });
});
term.onSelectionChange(() => _post({ t: "selection", payload: term.getSelection() }));

// Imperative globals the RN injectors call (see bridge.ts).
window.__ddFit = () => { _fit(); _post({ t: "resize", cols: term.cols, rows: term.rows }); };
window.__ddScroll = (lines) => term.scrollLines(lines);
window.__ddScrollPage = (dir) => term.scrollPages(dir);
window.__ddFocus = () => term.focus();

window.addEventListener("resize", () => window.__ddFit());
_post({ t: "ready", cols: term.cols, rows: term.rows });
`;

const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<style>
${xtermCss}
html, body { margin: 0; padding: 0; height: 100%; background: #0c0e10; overflow: hidden; }
#root { position: absolute; inset: 0; padding: 4px; }
</style>
</head>
<body>
<div id="root"></div>
<script>${xtermJs}</script>
<script>${fitJs}</script>
<script>${glue}</script>
</body>
</html>`;

const banner = `// GENERATED by src/features/terminals/scripts/build-xterm-host.ts — DO NOT EDIT BY HAND.
// Driver B's self-contained xterm.js host page (xterm + addon-fit inlined + the RN bridge glue).
// Re-generate after bumping @xterm/*:  bun run src/features/terminals/scripts/build-xterm-host.ts
`;

writeFileSync(out, `${banner}\nexport const XTERM_HOST_HTML = ${JSON.stringify(html)};\n`, "utf8");

// Self-verification (real, runnable here — only the on-device render is deferred).
const assertContains = (needle: string) => {
    if (!html.includes(needle)) {
        throw new Error(`generated host HTML missing expected token: ${needle}`);
    }
};

for (const token of ["new Terminal(", "FitAddon", "window.__ddFit", "window.__ddScroll", "RENDERER SWAP POINT"]) {
    assertContains(token);
}

console.log(`wrote ${out} (${html.length} bytes of HTML)`);
